
/*
SELECT TABLE_NAME,
count(*) TABLES
,concat(round(sum(table_rows)/1000000,2),'K') rows
,concat(round(sum(data_length)/(1024*1024*1024),2),'G') DATA
,concat(round(sum(index_length)/(1024*1024*1024),2),'G') idx
,concat(round(sum(data_length+index_length)/(1024*1024*1024),2),'G') total_size
,round(sum(index_length)/sum(data_length),2) idxfrac
FROM
information_schema.TABLES
where TABLE_SCHEMA = 'prod_asistencia_2014_05'
group by TABLE_NAME
order by data_length



/*
--DROP TABLE IF EXISTS proceso,
view_matricula_inicial_sep,
view_matricula_altas_sep,
view_matricula_bajas_sep,
view_matricula_final_sep,
view_matricula_inicial_multideficit,
view_matricula_altas_multideficit,
view_matricula_bajas_multideficit,
view_matricula_final_multideficit,
view_matricula_inicial_pie,
view_matricula_altas_pie,
view_matricula_bajas_pie,
view_matricula_final_pie,
view_matricula_inicial,
view_matricula_altas,
view_matricula_bajas,
view_matricula_final,
sige_alumno_excedente,
sige_asistencia,
sige_asistencia_declarada,
sige_curso_autorizado_nivel,
sige_curso_homologacion_subv,
sige_dias_trabajar,
sige_dias_trabajar_oficial,
sige_ee_convenio,
sige_ensenanza_grado_pie,
sige_establecimiento,
sige_matricula,
sige_estructura_curso,
sige_pie_alumnos,
sige_pie_alumnos_uns,
sige_pie_valores,
sige_prd_convenio_ee_seep,
sige_rbd_run_multideficit,
sige_region_deprov_comuna,
sige_run_duplicada,
sige_run_duplicada_asistencia,
sige_temp_asistencia_declarada,
sige_temp_curso_exedente,
sige_temp_matriculas_x_dia,
sige_ficha_alumno,
sige_asistencia_duplicada,
sige_asistencia_declarada_sep,
sige_asistencia_declarada_sep_poseidon,
sige_asistencia_declarada_pie,
sige_declaracion_asis,
sige_declaracion_certi,
sige_asistencia_declarada_multideficit,
tmp_ordena_lista


go


CREATE TABLE VIEW_MATRICULA_INICIAL_SEP(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_ALTAS_SEP(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_BAJAS_SEP(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_FINAL_SEP(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE VIEW_MATRICULA_INICIAL_MULTIDEFICIT(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    NIVEL               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,NIVEL)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_ALTAS_MULTIDEFICIT(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    NIVEL               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,NIVEL)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_BAJAS_MULTIDEFICIT(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    NIVEL               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,NIVEL)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_FINAL_MULTIDEFICIT(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    NIVEL               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,NIVEL)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_INICIAL_PIE(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS_SUBV               	INTEGER NOT NULL,
    COD_GRA_SUBV               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS_SUBV,COD_GRA_SUBV)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO




CREATE TABLE VIEW_MATRICULA_ALTAS_PIE(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS_SUBV               	INTEGER NOT NULL,
    COD_GRA_SUBV               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS_SUBV,COD_GRA_SUBV)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO



CREATE TABLE VIEW_MATRICULA_BAJAS_PIE(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS_SUBV               	INTEGER NOT NULL,
    COD_GRA_SUBV               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS_SUBV,COD_GRA_SUBV)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_FINAL_PIE(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_PAGO                INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS_SUBV               	INTEGER NOT NULL,
    COD_GRA_SUBV               	INTEGER NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS_SUBV,COD_GRA_SUBV)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE VIEW_MATRICULA_INICIAL(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_ALTAS(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE VIEW_MATRICULA_BAJAS(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE VIEW_MATRICULA_FINAL(
    ANO_ESCOLAR             INTEGER NOT NULL,
    MES_ESCOLAR             INTEGER NOT NULL,
    RBD                     INTEGER NOT NULL,
    COD_ENS               	INTEGER NOT NULL,
    COD_GRA               	INTEGER NOT NULL,
    LET_CUR                	VARCHAR(2) NOT NULL,
    MATRICULA              	INTEGER NOT NULL,
    PRIMARY KEY (ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO




CREATE TABLE SIGE_MATRICULA( 
	ANO_ESCOLAR               	INTEGER NOT NULL,
	SAL_RUN                   	VARCHAR(20) NOT NULL,
	RBD                       	INTEGER NOT NULL,
	COD_ENS                   	INTEGER NOT NULL,
	COD_GRA                   	INTEGER NOT NULL,
	LET_CUR                   	CHARACTER(2) NOT NULL,
	ESTADO_COLISION           	CHARACTER(1) NOT NULL,
	CONFIRMA_ASISTENCIA       	SMALLINT DEFAULT 0,
	ALUMNO_EXEDENTE           	SMALLINT DEFAULT 0,
	TIPO_ALUMNO               	SMALLINT DEFAULT 0,
	ESTADO_MATRICULA          	SMALLINT NOT NULL DEFAULT 0,
	FECHA_INCORPORACION       	DATE NOT NULL,
	FECHA_RETIRO              	DATE DEFAULT '1900-01-01',
	SAL_REPITE_GRADO          	SMALLINT DEFAULT 0,
	SAL_COD_PIE               	SMALLINT DEFAULT 0,
	SAL_DIFERENCIAL           	SMALLINT DEFAULT 0,
	COD_SEC                   	SMALLINT DEFAULT 0,
	COD_ESP                   	INTEGER DEFAULT 0,
	ORDEN_MATRICULA           	SMALLINT DEFAULT 0,
	PROMEDIO_FINAL            	DECIMAL(5,1) DEFAULT 0.0,
	PORCEN_ASISTENCIA         	SMALLINT DEFAULT 100,
	OBS_PROMOCION             	VARCHAR(100) DEFAULT '',
	REPRUEBA_ASISTENCIA       	SMALLINT NOT NULL DEFAULT 0,
	SITUACION_FINAL           	SMALLINT NOT NULL DEFAULT 0,
	FECHA_ULTIMA_ACTUALIZACION	DATE default '1900-01-01',
	FECHA_INGRESO_SISTEMA     	DATE default '1900-01-01',
	FECHA_RETIRO_SISTEMA      	DATE default '1900-01-01',
	PIE_FUENTE_FINAN          	SMALLINT NOT NULL DEFAULT 0,
	PIE_NRES                  	INTEGER NOT NULL DEFAULT 0,
	PIE_FECHA_RES             	DATE NOT NULL DEFAULT '1900-01-01',
	USER_INTERNO              	VARCHAR(30) NOT NULL DEFAULT '',
	IP_INTERNO                	VARCHAR(15) NOT NULL DEFAULT '0.0.0.0',
	HORA_ACTUALIZACION        	TIME ,
	IND_VULNERABLE            	SMALLINT DEFAULT 0,
	PRIMARY KEY(ANO_ESCOLAR,SAL_RUN,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_MATRICULA CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go
CREATE INDEX `IDX_GRUPO_1`
	ON `sige_matricula`(`ANO_ESCOLAR`, `RBD`, `COD_ENS`)
go
      
CREATE INDEX idx_asis_declarada 
	ON sige_matricula(ANO_ESCOLAR,   RBD, COD_ENS, COD_GRA, LET_CUR,SAL_RUN)
GO

create index  idx_grupo_2 
    on sige_matricula(ano_escolar,rbd,cod_ens,cod_gra,let_cur,sal_run)
go







CREATE TABLE SIGE_ESTRUCTURA_CURSO  ( 
	ANO_ESCOLAR               	INTEGER NOT NULL,
	RBD                       	INTEGER NOT NULL,
	COD_ENS                   	INTEGER NOT NULL,
	COD_GRA                   	INTEGER NOT NULL,
	LET_CUR                   	CHARACTER(2) NOT NULL,
	ESTADO_CURSO              	INTEGER NOT NULL,
	FECHA_CREACION            	DATE NOT NULL,
	FECHA_ELIMINACION         	DATE NOT NULL DEFAULT '1900-01-01',
	CURSO_COMBINADO           	SMALLINT NOT NULL,
	TIPO_JORNADA              	SMALLINT NOT NULL DEFAULT 0,
	DOC_RUN_JEFE              	VARCHAR(10) DEFAULT '',
	FECHA_ULTIMA_ACTUALIZACION	DATE ,
	DECRETO_CODIGO            	INTEGER DEFAULT 0,
	PLAN_RBD                  	INTEGER DEFAULT 0,
	PLAN_PROPIO               	SMALLINT DEFAULT 0,
	COD_PLAN_ESTUDIO          	VARCHAR(100) DEFAULT '01780',
	COD_SEC                   	SMALLINT DEFAULT 0,
	COD_ESP                   	INTEGER DEFAULT 0,
	COD_DES_CUR               	SMALLINT DEFAULT 0,
	ID_PLAN_ESTUDIO           	VARCHAR(27) NOT NULL DEFAULT '0',
	PLAN_ANO_ESCOLAR          	SMALLINT NOT NULL DEFAULT 1900,
	APLICA_JECD               	SMALLINT NOT NULL DEFAULT 0,
	HABILITADO_SUBV           	SMALLINT NOT NULL DEFAULT 0,
	OBSERVACION_ACTA          	VARCHAR(500) DEFAULT '',
	ESTADO_ACTA               	SMALLINT NOT NULL DEFAULT -100,
	TIPO_AULA                 	SMALLINT DEFAULT 1,
	ESTADO_HABILITACION       	SMALLINT DEFAULT 1,
	INFRAEST_ESPECIALIDAD     	SMALLINT NOT NULL DEFAULT 0,
	PRIMARY KEY(ANO_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

--ALTER TABLE SIGE_ESTRUCTURA_CURSO CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
--go



CREATE TABLE SIGE_ESTABLECIMIENTO  ( 
	RBD                  	INTEGER NOT NULL,
	DV_RBD               	INTEGER NOT NULL,
	NOMBRE_ESTA          	VARCHAR(150) NOT NULL,
	CP_REGION            	SMALLINT NOT NULL,
	CP_DEPROV            	SMALLINT NOT NULL,
	CP_PROVINCIA         	SMALLINT NOT NULL,
	CP_COMUNA            	SMALLINT NOT NULL,
	RUT_SOSTENEDOR       	VARCHAR(20) NOT NULL,
	COD_REGION           	SMALLINT NOT NULL,
	COD_PROVINCIA        	SMALLINT NOT NULL,
	COD_COMUNA           	SMALLINT NOT NULL,
	TIPO_DEPENDENCIA     	SMALLINT NOT NULL,
	ANO                  	SMALLINT NOT NULL,
	MES                  	SMALLINT NOT NULL,
	ESTADO_ESTAB         	SMALLINT NOT NULL,
	FONO_ESTAB           	VARCHAR(500) DEFAULT ' ',
	COD_AREA_ESTAB       	VARCHAR(3) DEFAULT '00',
	MAIL_ESTAB           	VARCHAR(100) DEFAULT '',
	N_RES_RECOFI         	VARCHAR(100) DEFAULT ' ',
	FECHA_RES_RECOFI     	DATE DEFAULT '1900-01-01',
	DIRE_RUN             	VARCHAR(10) DEFAULT '',
	DIRE_DV              	CHARACTER(1) DEFAULT '',
	DIRE_PATERNO         	VARCHAR(100) DEFAULT ' ',
	DIRE_MATERNO         	VARCHAR(100) DEFAULT ' ',
	DIRE_NOMBRES         	VARCHAR(100) DEFAULT ' ',
	ESTADO_ACTUALIZACION 	SMALLINT DEFAULT 0,
	N_RES_NOMBRE         	VARCHAR(100) DEFAULT ' ',
	FECHA_RES_NOMBRE     	DATE DEFAULT '1900-01-01',
	DIRECCION_ESTAB      	VARCHAR(500) DEFAULT ' ',
	CELULAR_ESTAB        	VARCHAR(10) DEFAULT ' ',
	FECHA_ACTUALIZACION  	DATE ,
	ESTADO_RECOFI        	SMALLINT DEFAULT 0,
	ASISTENCIA_SEP       	SMALLINT DEFAULT 0,
	IND_CONVENIO         	SMALLINT NOT NULL DEFAULT 0,
	ANO_CONVENIO         	SMALLINT NOT NULL DEFAULT 0,
	RURAL_ESTAB          	INTEGER DEFAULT 0,
	TIENE_CLAVE_SUB      	SMALLINT DEFAULT 0,
	CLAVE_ESTAB          	VARCHAR(100) ,
	REGIMEN_SEP          	SMALLINT DEFAULT 0,
	CLASIFICACION        	SMALLINT DEFAULT 0,
	ASISTENCIA_NORMAL    	SMALLINT DEFAULT 0,
	DIRE_CLAVE           	VARCHAR(100) DEFAULT '',
	DIRE_CLAVE_VALIDA    	SMALLINT DEFAULT 0,
	SW_PROPIO            	VARCHAR(250) DEFAULT '',
	DIRECCION_ESTAB_NUM  	VARCHAR(10) DEFAULT 'S/N',
	LUGAR_REFERENCIA     	VARCHAR(200) DEFAULT ' ',
	POSTAL_CODE          	VARCHAR(15) DEFAULT ' ',
	COD_AREA_DIRECTOR    	VARCHAR(3) DEFAULT '0',
	TELEFONO_DIRECTOR    	VARCHAR(15) DEFAULT '0',
	CELULAR_DIRECTOR     	VARCHAR(15) DEFAULT ' ',
	MAIL_DIRECTOR        	VARCHAR(200) DEFAULT '@',
	TIPO_ESTA            	SMALLINT DEFAULT 1,
	USER_INTERNO         	VARCHAR(30) DEFAULT 'ADM',
	IP_INTERNO           	VARCHAR(15) DEFAULT '0.0.0.0',
	HORA_ACTUALIZACION   	TIME ,
	TIPO_FINANCIAMENTO   	SMALLINT DEFAULT 0,
	PORC_ZONA            	INTEGER DEFAULT 0,
	PISO_RURAL           	SMALLINT DEFAULT 0,
	INC_RURALIDAD        	SMALLINT DEFAULT 0,
	ING_PROYECTADOS      	INTEGER DEFAULT 0,
	ING_PERSIBIDOS       	INTEGER DEFAULT 0,
	DICL_INTEROP         	SMALLINT NOT NULL DEFAULT 0,
	TIPO_ALUMNADO        	SMALLINT DEFAULT 0,
	CAPACIDAD_HOMBRES    	INTEGER DEFAULT 0,
	CAPACIDAD_MUJERES    	INTEGER DEFAULT 0,
	FECHA_INGRESO_SISTEMA	DATE ,
	HORA_INGRESO_SISTEMA 	TIME ,
	FECHA_INI_RECOFI     	DATE DEFAULT '1900-01-01',
	FECHA_FIN_RECOFI     	DATE DEFAULT '1900-01-01',
	TIPO_DOCUMENTO_RECOFI	VARCHAR(27) DEFAULT '',
	URL_DOC_RECOFI       	VARCHAR(150) DEFAULT '',
	PER_ID               	VARCHAR(27) DEFAULT '',
	TREL_TIPO            	SMALLINT DEFAULT 0,
	FECHA_RECIBE_SUBV    	DATE DEFAULT '1900-01-01',
	PRIMARY KEY(RBD)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_CURSO_AUTORIZADO_NIVEL  ( 
	ANO_ESCOLAR        	INTEGER NOT NULL,
	RBD                	INTEGER NOT NULL,
	COD_ENS            	SMALLINT NOT NULL,
	COD_GRA            	SMALLINT NOT NULL,
	CCJECD             	SMALLINT NOT NULL,
	CSJECD             	SMALLINT NOT NULL,
	DEPENDENCIA        	SMALLINT NOT NULL,
	FECHA_JECD         	DATE NOT NULL,
	RESOL_JECD         	VARCHAR(20) NOT NULL,
	USER_INTERNO       	VARCHAR(30) NOT NULL,
	IP_INTERNO         	VARCHAR(15) NOT NULL,
	FECHA_ACTUALIZACION	DATE ,
	HORA_ACTUALIZACION 	TIME ,
	PRIMARY KEY(ANO_ESCOLAR,RBD,COD_ENS,COD_GRA)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_DIAS_TRABAJAR_OFICIAL  ( 
	REGION             	SMALLINT,
	DEPROV             	SMALLINT,
	MES_ESCOLAR        	SMALLINT,
	ANO_ESCOLAR        	SMALLINT,
	RBD                	INTEGER NOT NULL,
	COD_ENS            	SMALLINT,
	COD_GRA            	SMALLINT,
	LET_CUR            	VARCHAR(2),
	DIA1               	SMALLINT,
	DIA2               	SMALLINT,
	DIA3               	SMALLINT,
	DIA4               	SMALLINT,
	DIA5               	SMALLINT,
	DIA6               	SMALLINT,
	DIA7               	SMALLINT,
	DIA8               	SMALLINT,
	DIA9               	SMALLINT,
	DIA10              	SMALLINT,
	DIA11              	SMALLINT,
	DIA12              	SMALLINT,
	DIA13              	SMALLINT,
	DIA14              	SMALLINT,
	DIA15              	SMALLINT,
	DIA16              	SMALLINT,
	DIA17              	SMALLINT,
	DIA18              	SMALLINT,
	DIA19              	SMALLINT,
	DIA20              	SMALLINT,
	DIA21              	SMALLINT,
	DIA22              	SMALLINT,
	DIA23              	SMALLINT,
	DIA24              	SMALLINT,
	DIA25              	SMALLINT,
	DIA26              	SMALLINT,
	DIA27              	SMALLINT,
	DIA28              	SMALLINT,
	DIA29              	SMALLINT,
	DIA30              	SMALLINT,
	DIA31              	SMALLINT,
	FECHA_ACTUALIZACION	DATE ,
	HORA_ACTUALIZACION 	TIME ,
	DIAS_TRABAJADOS    	SMALLINT DEFAULT 0,
	N_RESOLUCION       	VARCHAR(20) ,
	FECHA_RESOLUCION   	DATE ,
	USER_INTERNO       	VARCHAR(30) ,
	IP_INTERNO         	VARCHAR(15) ,
	PRIMARY KEY(ANO_ESCOLAR,MES_ESCOLAR,REGION,DEPROV,RBD,COD_ENS,COD_GRA,LET_CUR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_DIAS_TRABAJAR_OFICIAL CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go

CREATE TABLE SIGE_DIAS_TRABAJAR  ( 
	MES_ESCOLAR       	SMALLINT NOT NULL,
	ANO_ESCOLAR       	SMALLINT NOT NULL,
	RBD               	INTEGER NOT NULL,
	COD_ENS           	SMALLINT NOT NULL,
	COD_GRA           	SMALLINT NOT NULL,
	LET_CUR           	VARCHAR(2) NOT NULL,
	DIA1              	SMALLINT,
	DIA2              	SMALLINT,
	DIA3              	SMALLINT,
	DIA4              	SMALLINT,
	DIA5              	SMALLINT,
	DIA6              	SMALLINT,
	DIA7              	SMALLINT,
	DIA8              	SMALLINT,
	DIA9              	SMALLINT,
	DIA10             	SMALLINT,
	DIA11             	SMALLINT,
	DIA12             	SMALLINT,
	DIA13             	SMALLINT,
	DIA14             	SMALLINT,
	DIA15             	SMALLINT,
	DIA16             	SMALLINT,
	DIA17             	SMALLINT,
	DIA18             	SMALLINT,
	DIA19             	SMALLINT,
	DIA20             	SMALLINT,
	DIA21             	SMALLINT,
	DIA22             	SMALLINT,
	DIA23             	SMALLINT,
	DIA24             	SMALLINT,
	DIA25             	SMALLINT,
	DIA26             	SMALLINT,
	DIA27             	SMALLINT,
	DIA28             	SMALLINT,
	DIA29             	SMALLINT,
	DIA30             	SMALLINT,
	DIA31             	SMALLINT,
	FECHA_MOD         	DATE ,
	HRA_MOD           	TIME ,
	DIAS_TRABAJADOS   	SMALLINT DEFAULT 0,
	ESTADO_DECLARACION	SMALLINT,
	AUT_DEPROV        	SMALLINT DEFAULT 0 
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_DIAS_TRABAJAR CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go



CREATE TABLE SIGE_ASISTENCIA  ( 
	MES_ESCOLAR        	SMALLINT NOT NULL,
	RBD                	INTEGER NOT NULL,
	COD_ENS            	SMALLINT NOT NULL,
	COD_GRA            	SMALLINT NOT NULL,
	LET_CUR            	VARCHAR(2) NOT NULL,
	ANO_ESCOLAR        	INTEGER NOT NULL,
	SAL_RUN            	VARCHAR(20) NOT NULL,
	DIA1               	SMALLINT,
	DIA2               	SMALLINT,
	DIA3               	SMALLINT,
	DIA4               	SMALLINT,
	DIA5               	SMALLINT,
	DIA6               	SMALLINT,
	DIA7               	SMALLINT,
	DIA8               	SMALLINT,
	DIA9               	SMALLINT,
	DIA10              	SMALLINT,
	DIA11              	SMALLINT,
	DIA12              	SMALLINT,
	DIA13              	SMALLINT,
	DIA14              	SMALLINT,
	DIA15              	SMALLINT,
	DIA16              	SMALLINT,
	DIA17              	SMALLINT,
	DIA18              	SMALLINT,
	DIA19              	SMALLINT,
	DIA20              	SMALLINT,
	DIA21              	SMALLINT,
	DIA22              	SMALLINT,
	DIA23              	SMALLINT,
	DIA24              	SMALLINT,
	DIA25              	SMALLINT,
	DIA26              	SMALLINT,
	DIA27              	SMALLINT,
	DIA28              	SMALLINT,
	DIA29              	SMALLINT,
	DIA30              	SMALLINT,
	DIA31              	SMALLINT,
	DIAS_TRABAJADOS    	SMALLINT,
	ASIS_PROMEDIO      	DECIMAL(10,4),
	ESTADO_DECLARACION 	SMALLINT DEFAULT 0,
	DIAS_ASISTIDOS     	SMALLINT,
	USER_INTERNO       	VARCHAR(30) NOT NULL DEFAULT '',
	IP_INTERNO         	VARCHAR(15) NOT NULL DEFAULT '0.0.0.0',
	FECHA_ACTUALIZACION	DATE ,
	HORA_ACTUALIZACION 	TIME ,
	CUR_AUT_ESTADO     	SMALLINT ,
	PRIMARY KEY(ANO_ESCOLAR,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

--ALTER TABLE SIGE_ASISTENCIA CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go


CREATE TABLE SIGE_PIE_ALUMNOS  ( 
	ANO_ESCOLAR        	INTEGER NOT NULL,
	RBD                	INTEGER NOT NULL,
	COD_ENS            	INTEGER NOT NULL,
	COD_GRA            	INTEGER NOT NULL,
	LET_CUR            	VARCHAR(2) NOT NULL,
	JECD               	SMALLINT NOT NULL,
	SAL_RUN            	VARCHAR(20) NOT NULL,
	TIPO_PIE           	SMALLINT NOT NULL,
	COD_PIE            	SMALLINT NOT NULL,
	ESTADO             	SMALLINT NOT NULL,
	ANO_ANTERIOR       	SMALLINT NOT NULL,
	FECHA_ACTUALIZACION	DATE NOT NULL,
	HORA_ACTUALIZACION 	TIME NOT NULL,
	CONVENIO           	SMALLINT DEFAULT 0,
	PRIMARY KEY(ANO_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,JECD,SAL_RUN)
)
engine=myIsam
COLLATE utf8_spanish_ci
go
--ALTER TABLE SIGE_PIE_ALUMNOS CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go



CREATE TABLE SIGE_REGION_DEPROV_COMUNA  ( 
	COD_REGION  	INTEGER,
	NOM_REGION  	CHARACTER(50),
	COD_DEPROV  	INTEGER,
	NOM_DEPROV  	CHARACTER(50),
	COD_COMUNA  	INTEGER,
	NOM_COMUNA  	CHARACTER(50),
	ORDENAMIENTO	SMALLINT DEFAULT 0 
	)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_RBD_RUN_MULTIDEFICIT  ( 
	ANO_ESCOLAR   	INTEGER NOT NULL,
	RBD           	INTEGER NOT NULL,
	SAL_RUN       	VARCHAR(20) NOT NULL,
	FECHA_INICIO  	DATE ,
	FECHA_TERMINO 	DATE ,
	FECHA_CREACION	DATE ,
	PRIMARY KEY(ANO_ESCOLAR,RBD,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE SIGE_PIE_ALUMNOS_UNS  ( 
	ANO_ESCOLAR        	INTEGER NOT NULL,
	MES_PAGO           	INTEGER NOT NULL,
	RBD                	INTEGER NOT NULL,
	COD_ENS            	INTEGER NOT NULL,
	COD_GRA            	INTEGER NOT NULL,
	LET_CUR            	VARCHAR(2) NOT NULL,
	JECD               	SMALLINT NOT NULL,
	SAL_RUN            	VARCHAR(20) NOT NULL,
	TIPO_PIE           	SMALLINT NOT NULL,
	COD_PIE            	SMALLINT NOT NULL,
	ESTADO             	SMALLINT NOT NULL,
	ANO_ANTERIOR       	SMALLINT NOT NULL,
	FECHA_ACTUALIZACION	DATE NOT NULL,
	HORA_ACTUALIZACION 	TIME NOT NULL,
	CONVENIO           	SMALLINT DEFAULT 0,
	FECHA_INGRESO_UNS  	DATE ,
	TIME_INGRESO_UNS   	TIME ,
	PRIMARY KEY(ANO_ESCOLAR,MES_PAGO,RBD,COD_ENS,COD_GRA,LET_CUR,JECD,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_PIE_ALUMNOS_UNS CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
go


CREATE TABLE SIGE_PRD_CONVENIO_EE_SEEP  ( 
	RBD           	INTEGER NOT NULL,
	NOMBRE        	VARCHAR(100),
	ANIO_PROC     	INTEGER NOT NULL DEFAULT 0,
	ANIO_MATRICULA	INTEGER NOT NULL DEFAULT 0,
	CONCENTRACION 	DECIMAL(10,4) DEFAULT 0.0,
	PROMEDIO_AP   	DECIMAL(10,4) DEFAULT 0.0,
	PROMEDIO_TOTAL	DECIMAL(10,4) DEFAULT 0.0,
    PRIMARY KEY(ANIO_PROC,RBD)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE SIGE_PIE_VALORES  ( 
	ANO_ESCOLAR	INTEGER NOT NULL,
	TIPO_PIE   	SMALLINT NOT NULL,
	COD_PIE    	SMALLINT NOT NULL,
	GLOSA_PIE  	VARCHAR(100) NOT NULL,
	ESTADO     	SMALLINT NOT NULL,
	PRIMARY KEY(TIPO_PIE,COD_PIE,ANO_ESCOLAR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_FICHA_ALUMNO  ( 
	SAL_RUN               	VARCHAR(20) NOT NULL,
	SAL_DGV               	CHARACTER(1) ,
	SAL_APP               	VARCHAR(50) ,
	SAL_APM               	VARCHAR(50) ,
	SAL_NOM               	VARCHAR(100),
	SAL_GENERO            	CHARACTER(1) ,
	SAL_FEC_NAC           	DATE ,
	ESTADO_CIVIL          	CHARACTER(1) ,
	SAL_MAIL              	VARCHAR(100) ,
	SAL_DIR               	VARCHAR(100) ,
	SAL_FEC_DEFUN         	DATE ,
	SAL_NACIONALIDAD      	CHARACTER(1) ,
	SAL_FEC_MATR          	DATE ,
	IND_VALREGCIVIL       	INTEGER ,
	SAL_FONO              	VARCHAR(20) ,
	SAL_CELULAR           	VARCHAR(20) ,
	FEC_ULTIMA_ACT        	DATE ,
	HRA_ULTIMA_ACT        	TIME ,
	SAL_COD_COMUNA        	SMALLINT,
	SAL_COD_REGION        	SMALLINT,
	SAL_ESTADO            	SMALLINT ,
	COD_ETNIA             	SMALLINT DEFAULT 0,
	SAL_EMBARAZO          	SMALLINT DEFAULT 0,
	TIPO_ALUMNO           	SMALLINT DEFAULT 0,
	SOLICITA_VALIDACION   	SMALLINT DEFAULT 0,
	SAL_DIR_NUMERO        	VARCHAR(20) ,
	SAL_DIR_NUM_DEPTO_CASA	VARCHAR(20) ,
	SAL_DIR_INFO_ADICIONAL	VARCHAR(100) ,
	SAL_PAIS_ORIGEN       	SMALLINT ,
	PRIMARY KEY(SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_CURSO_HOMOLOGACION_SUBV  ( 
	ANO_ESCOLAR 	INTEGER NOT NULL,
	COD_ENS     	INTEGER NOT NULL,
	COD_GRA     	INTEGER NOT NULL,
	APLICA_JECD 	SMALLINT NOT NULL DEFAULT 0,
	TIPO_AULA   	SMALLINT NOT NULL DEFAULT 1,
	COD_ENS_SUBV	INTEGER NOT NULL,
	COD_GRA_SUBV	INTEGER NOT NULL,
	PRIMARY KEY(ANO_ESCOLAR,COD_ENS,COD_GRA,APLICA_JECD,TIPO_AULA,COD_ENS_SUBV,COD_GRA_SUBV)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_ENSENANZA_GRADO_PIE  ( 
	COD_ENSENANZA	SMALLINT NOT NULL,
	ANO_ESCOLAR  	SMALLINT ,
	COD_GRADO    	SMALLINT NOT NULL,
	GLOSA_GRADO  	VARCHAR(100) NOT NULL,
	JECD         	SMALLINT NOT NULL DEFAULT 0,
	TIPO_DEFICIT 	SMALLINT NOT NULL DEFAULT 0,
	DISCAPACIDAD 	SMALLINT NOT NULL DEFAULT 0,
	ESTADO_GRADO 	SMALLINT NOT NULL DEFAULT 1,
	COD_ENS_SUBV 	SMALLINT NOT NULL DEFAULT 0,
	MATRICULA_MAX	SMALLINT NOT NULL DEFAULT 0,
	NIVEL        	SMALLINT DEFAULT 0,
	PRIMARY KEY(COD_ENSENANZA,ANO_ESCOLAR,COD_GRADO,JECD,TIPO_DEFICIT,DISCAPACIDAD)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_ASISTENCIA_DECLARADA  ( 
	MES_PAGO          	SMALLINT NOT NULL,
	MES_ESCOLAR       	SMALLINT NOT NULL,
	RBD               	INTEGER NOT NULL,
	COD_ENS           	SMALLINT NOT NULL,
	COD_GRA           	SMALLINT NOT NULL,
	LET_CUR           	VARCHAR(2) NOT NULL,
	ANO_ESCOLAR       	INTEGER NOT NULL,
	SAL_RUN           	VARCHAR(20) NOT NULL,
	DIA1              	SMALLINT,
	DIA2              	SMALLINT,
	DIA3              	SMALLINT,
	DIA4              	SMALLINT,
	DIA5              	SMALLINT,
	DIA6              	SMALLINT,
	DIA7              	SMALLINT,
	DIA8              	SMALLINT,
	DIA9              	SMALLINT,
	DIA10             	SMALLINT,
	DIA11             	SMALLINT,
	DIA12             	SMALLINT,
	DIA13             	SMALLINT,
	DIA14             	SMALLINT,
	DIA15             	SMALLINT,
	DIA16             	SMALLINT,
	DIA17             	SMALLINT,
	DIA18             	SMALLINT,
	DIA19             	SMALLINT,
	DIA20             	SMALLINT,
	DIA21             	SMALLINT,
	DIA22             	SMALLINT,
	DIA23             	SMALLINT,
	DIA24             	SMALLINT,
	DIA25             	SMALLINT,
	DIA26             	SMALLINT,
	DIA27             	SMALLINT,
	DIA28             	SMALLINT,
	DIA29             	SMALLINT,
	DIA30             	SMALLINT,
	DIA31             	SMALLINT,
	DIAS_TRABAJADOS   	SMALLINT,
	ASIS_PROMEDIO     	DECIMAL(10,4),
	ESTADO_DECLARACION	SMALLINT DEFAULT 0,
	DIAS_ASISTIDOS    	SMALLINT,
	ESTADO_PAGO       	SMALLINT DEFAULT 0,
	FECHA_MATRICULA   	date DEFAULT '1900-01-01',
	ESTADO_COLISION   	SMALLINT DEFAULT 0,
	REGIMEN_SEP       	SMALLINT DEFAULT 0,
	TIPO_ALUMNO       	SMALLINT DEFAULT 0,
	ORDEN_MATRICULA   	SMALLINT DEFAULT 0,
	TIPO_AULA         	SMALLINT DEFAULT 1,
	JECD              	SMALLINT DEFAULT -100,
	COD_ENS_SUBV      	INTEGER DEFAULT 0,
	COD_GRA_SUBV      	INTEGER DEFAULT 0,
	MONTO_SUBV_NORMAL 	DECIMAL(20,5) DEFAULT 0,
	HABILITADO_SUBV   	SMALLINT DEFAULT 0,
	FECHA_INGRESO     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

--ALTER TABLE SIGE_ASISTENCIA_DECLARADA CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
--go

CREATE INDEX idx_sep 
	ON sige_asistencia_declarada(ANO_ESCOLAR, MES_PAGO, MES_ESCOLAR, REGIMEN_SEP, TIPO_ALUMNO, ESTADO_PAGO, HABILITADO_SUBV, ESTADO_DECLARACION, COD_ENS, COD_GRA)
GO
CREATE INDEX idx_hospitalarios  
	ON sige_asistencia_declarada(ANO_ESCOLAR, MES_PAGO, MES_ESCOLAR,TIPO_AULA,HABILITADO_SUBV,ESTADO_PAGO, ESTADO_DECLARACION)
GO




CREATE TABLE SIGE_EE_CONVENIO  ( 
	CONV_ID                	VARCHAR(27) NOT NULL,
	CONV_TIPO_ID           	VARCHAR(27) NOT NULL,
	RBD                    	INTEGER NOT NULL,
	CONV_VALOR             	VARCHAR(50),
	CONV_VALOR_DESC        	VARCHAR(150),
	CONV_FOLIO             	VARCHAR(50),
	CONV_FECHA_FOLIO       	DATE,
	CONV_FECHA_INI_CONVEN  	DATE,
	CONV_FECHA_FIN_CONVEN  	DATE,
	CONV_FOLIO_FECHA_FIN   	DATE,
	CONV_FOLIO_FIN         	VARCHAR(50),
	CONV_DESCRIPCION       	VARCHAR(500),
	CONV_ESTADO            	SMALLINT,
	CONV_FECHA_CREACION    	DATE,
	CONV_HORA_CREACION     	TIME,
	CONV_FECHA_MODICACION  	DATE,
	CONV_HORA_MODICACION   	TIME,
	CONV_TIPO_DOCUMENTO_SGD	VARCHAR(27),
	CONV_DOC_SGD           	VARCHAR(100),
	CONV_ESTADO_SICPS      	VARCHAR(1) NOT NULL DEFAULT 0,
	CONV_USER_INTERNO      	VARCHAR(30),
	CONV_IP_INTERNO        	VARCHAR(15),
	CONV_FOLIO_FECHA_INI   	DATE NOT NULL DEFAULT '1900-01-01',
	PRIMARY KEY(RBD,CONV_TIPO_ID,CONV_ID)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_ALUMNO_EXCEDENTE  ( 
	ID_AE       	VARCHAR(27) NOT NULL,
	ANO_ESCOLAR 	INTEGER NOT NULL,
	SAL_RUN     	VARCHAR(10) NOT NULL,
	RBD         	INTEGER NOT NULL,
	COD_ENS     	INTEGER NOT NULL,
	COD_GRA     	SMALLINT NOT NULL,
	LET_CUR     	VARCHAR(2) NOT NULL,
	FECHA_INICIO	DATE NOT NULL,
	FECHA_FIN   	DATE DEFAULT '1900-01-01',
	PRIMARY KEY(ID_AE)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_ALUMNO_EXCEDENTE CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
--go

create index  idx_SIGE_ALUMNO_EXCEDENTE on SIGE_ALUMNO_EXCEDENTE(ano_escolar,sal_run,rbd,cod_ens,cod_gra,let_cur)

CREATE TABLE SIGE_TEMP_MATRICULAS_X_DIA  ( 
	MES_PAGO   	SMALLINT NOT NULL,
	MES_ESCOLAR	SMALLINT NOT NULL,
	RBD        	INTEGER NOT NULL,
	COD_ENS    	SMALLINT NOT NULL,
	COD_GRA    	SMALLINT NOT NULL,
	LET_CUR    	VARCHAR(2) NOT NULL,
	DIA1       	INTEGER,
	DIA2       	INTEGER,
	DIA3       	INTEGER,
	DIA4       	INTEGER,
	DIA5       	INTEGER,
	DIA6       	INTEGER,
	DIA7       	INTEGER,
	DIA8       	INTEGER,
	DIA9       	INTEGER,
	DIA10      	INTEGER,
	DIA11      	INTEGER,
	DIA12      	INTEGER,
	DIA13      	INTEGER,
	DIA14      	INTEGER,
	DIA15      	INTEGER,
	DIA16      	INTEGER,
	DIA17      	INTEGER,
	DIA18      	INTEGER,
	DIA19      	INTEGER,
	DIA20      	INTEGER,
	DIA21      	INTEGER,
	DIA22      	INTEGER,
	DIA23      	INTEGER,
	DIA24      	INTEGER,
	DIA25      	INTEGER,
	DIA26      	INTEGER,
	DIA27      	INTEGER,
	DIA28      	INTEGER,
	DIA29      	INTEGER,
	DIA30      	INTEGER,
	DIA31      	INTEGER 
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO
--ALTER TABLE SIGE_TEMP_MATRICULAS_X_DIA CONVERT TO CHARACTER SET utf8 COLLATE utf8_spanish_ci
--go



CREATE TABLE SIGE_TEMP_ASISTENCIA_DECLARADA( 
	MES_PAGO          	SMALLINT NOT NULL,
	MES_ESCOLAR       	SMALLINT NOT NULL,
	RBD               	INTEGER NOT NULL,
	COD_ENS           	SMALLINT NOT NULL,
	COD_GRA           	SMALLINT NOT NULL,
	LET_CUR           	VARCHAR(2) NOT NULL,
	ANO_ESCOLAR       	INTEGER NOT NULL,
	SAL_RUN           	VARCHAR(20) NOT NULL,
	DIA1              	SMALLINT,
	DIA2              	SMALLINT,
	DIA3              	SMALLINT,
	DIA4              	SMALLINT,
	DIA5              	SMALLINT,
	DIA6              	SMALLINT,
	DIA7              	SMALLINT,
	DIA8              	SMALLINT,
	DIA9              	SMALLINT,
	DIA10             	SMALLINT,
	DIA11             	SMALLINT,
	DIA12             	SMALLINT,
	DIA13             	SMALLINT,
	DIA14             	SMALLINT,
	DIA15             	SMALLINT,
	DIA16             	SMALLINT,
	DIA17             	SMALLINT,
	DIA18             	SMALLINT,
	DIA19             	SMALLINT,
	DIA20             	SMALLINT,
	DIA21             	SMALLINT,
	DIA22             	SMALLINT,
	DIA23             	SMALLINT,
	DIA24             	SMALLINT,
	DIA25             	SMALLINT,
	DIA26             	SMALLINT,
	DIA27             	SMALLINT,
	DIA28             	SMALLINT,
	DIA29             	SMALLINT,
	DIA30             	SMALLINT,
	DIA31             	SMALLINT,
	DIAS_TRABAJADOS   	SMALLINT,
	ASIS_PROMEDIO     	DECIMAL(10,4),
	ESTADO_DECLARACION	SMALLINT DEFAULT 0,
	DIAS_ASISTIDOS    	SMALLINT,
	ESTADO_PAGO       	SMALLINT DEFAULT 0,
	FECHA_MATRICULA   	DATE DEFAULT '1900-01-01',
	ESTADO_COLISION   	SMALLINT DEFAULT 0,
	REGIMEN_SEP       	SMALLINT DEFAULT 0,
	TIPO_ALUMNO       	SMALLINT DEFAULT 0,
	ORDEN_MATRICULA   	SMALLINT DEFAULT 0,
	TIPO_AULA         	SMALLINT DEFAULT 1,
	JECD              	SMALLINT DEFAULT -100,
	COD_ENS_SUBV      	INTEGER DEFAULT 0,
	COD_GRA_SUBV      	INTEGER DEFAULT 0,
	MONTO_SUBV_NORMAL 	DECIMAL(20,5) DEFAULT 0,
	PRIMARY KEY(MES_PAGO,COD_GRA,LET_CUR,MES_ESCOLAR,RBD,COD_ENS,ANO_ESCOLAR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO





CREATE TABLE SIGE_TEMP_CURSO_EXEDENTE  ( 
	MES_PAGO   	SMALLINT NOT NULL,
	MES_ESCOLAR	SMALLINT NOT NULL,
	RBD        	INTEGER NOT NULL,
	COD_ENS    	SMALLINT NOT NULL,
	COD_GRA    	SMALLINT NOT NULL,
	LET_CUR    	VARCHAR(2) NOT NULL,
	ANO_ESCOLAR	INTEGER NOT NULL,
	ESTADO_PAGO	SMALLINT DEFAULT 0,
	PRIMARY KEY(MES_PAGO,COD_GRA,LET_CUR,MES_ESCOLAR,RBD,COD_ENS,ANO_ESCOLAR)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO




create table proceso(
    ano_escolar   int default 0,
    mes_pago      int default 0,
    mes_escolar   int default 0,
    descripcion   varchar(100),
    fecha         TIMESTAMP DEFAULT CURRENT_TIMESTAMP          
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

CREATE TABLE SIGE_RUN_DUPLICADA  ( 
	ANO_ESCOLAR	INTEGER NOT NULL,
	MES_PAGO   	INTEGER NOT NULL,
	SAL_RUN    	VARCHAR(20) NOT NULL 
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

create index  idx_sige_run_duplicada on sige_run_duplicada(ano_escolar,mes_pago,sal_run)
go

CREATE TABLE SIGE_RUN_DUPLICADA_ASISTENCIA  ( 
	MES_PAGO          	SMALLINT NOT NULL,
	MES_ESCOLAR       	SMALLINT NOT NULL,
	RBD               	INTEGER NOT NULL,
	COD_ENS           	SMALLINT NOT NULL,
	COD_GRA           	SMALLINT NOT NULL,
	LET_CUR           	VARCHAR(2) NOT NULL,
	ANO_ESCOLAR       	INTEGER NOT NULL,
	SAL_RUN           	VARCHAR(20) NOT NULL,
	DIA1              	SMALLINT,
	DIA2              	SMALLINT,
	DIA3              	SMALLINT,
	DIA4              	SMALLINT,
	DIA5              	SMALLINT,
	DIA6              	SMALLINT,
	DIA7              	SMALLINT,
	DIA8              	SMALLINT,
	DIA9              	SMALLINT,
	DIA10             	SMALLINT,
	DIA11             	SMALLINT,
	DIA12             	SMALLINT,
	DIA13             	SMALLINT,
	DIA14             	SMALLINT,
	DIA15             	SMALLINT,
	DIA16             	SMALLINT,
	DIA17             	SMALLINT,
	DIA18             	SMALLINT,
	DIA19             	SMALLINT,
	DIA20             	SMALLINT,
	DIA21             	SMALLINT,
	DIA22             	SMALLINT,
	DIA23             	SMALLINT,
	DIA24             	SMALLINT,
	DIA25             	SMALLINT,
	DIA26             	SMALLINT,
	DIA27             	SMALLINT,
	DIA28             	SMALLINT,
	DIA29             	SMALLINT,
	DIA30             	SMALLINT,
	DIA31             	SMALLINT,
	DIAS_TRABAJADOS   	SMALLINT,
	ASIS_PROMEDIO     	DECIMAL(10,4),
	ESTADO_DECLARACION	SMALLINT,
	DIAS_ASISTIDOS    	SMALLINT,
	FECHA_MATRICULA   	DATE,
	REGIMEN_SEP       	SMALLINT,
	TIPO_ALUMNO       	SMALLINT,
	ORDEN_MATRICULA   	SMALLINT,
	TIPO_AULA         	SMALLINT,
	JECD              	SMALLINT,
	COD_ENS_SUBV      	INTEGER,
	COD_GRA_SUBV      	INTEGER,
	MONTO_SUBV_NORMAL 	DECIMAL(20,5) 
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO



create index  idx_sige_run_duplicada_asistencia on sige_run_duplicada_asistencia(mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur,sal_run,ano_escolar)
go
create index  idx1_sige_run_duplicada on sige_run_duplicada_asistencia(sal_run)
go


CREATE TABLE SIGE_ASISTENCIA_DUPLICADA  ( 
	ID                     	VARCHAR(36) NOT NULL,
	ANO_ESCOLAR            	SMALLINT NOT NULL,
	MES_PAGO               	SMALLINT NOT NULL,
	MES_ESCOLAR            	SMALLINT NOT NULL,
	RBD                    	INTEGER NOT NULL,
	COD_ENS                	SMALLINT NOT NULL,
	COD_GRA                	SMALLINT NOT NULL,
	LET_CUR                	VARCHAR(2) NOT NULL,
	SAL_RUN                	VARCHAR(20) NOT NULL,
	DIAS_TRABAJADOS        	VARCHAR(250) NOT NULL DEFAULT '',
	DIAS_TRABAJADOS_PALABRA	VARCHAR(4000) NOT NULL DEFAULT '',
	ASIS_PROMEDIO          	DECIMAL(10,4),
	ESTADO_DECLARACION     	SMALLINT DEFAULT 0,
	DIAS_ASISTIDOS         	SMALLINT,
	ESTADO                 	SMALLINT DEFAULT 1,
	PRIMARY KEY(ID)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


create table tmp_ordena_lista  ( 
    ano_escolar       	integer not null,
    mes_pago          	smallint not null,
    mes_escolar       	smallint not null,
	rbd               	integer not null,
	cod_ens           	smallint not null,
	cod_gra           	smallint not null,
	let_cur           	varchar(2) not null,
	sal_run           	varchar(20) not null,
	orden_matricula   	smallint default 0,
    orden_final        	smallint default 0,
    primary key(ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur,sal_run)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO

create index  idx_tmp on tmp_ordena_lista(ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur,sal_run);



CREATE TABLE sige_asistencia_declarada_sep  ( 
	MES_PAGO          	smallint(6) NOT NULL,
	MES_ESCOLAR       	smallint(6) NOT NULL,
	RBD               	int(11) NOT NULL,
	COD_ENS           	smallint(6) NOT NULL,
	COD_GRA           	smallint(6) NOT NULL,
	LET_CUR           	varchar(2) NOT NULL,
	ANO_ESCOLAR       	int(11) NOT NULL,
	SAL_RUN           	varchar(20) NOT NULL,
	DIA1              	smallint(6) NULL,
	DIA2              	smallint(6) NULL,
	DIA3              	smallint(6) NULL,
	DIA4              	smallint(6) NULL,
	DIA5              	smallint(6) NULL,
	DIA6              	smallint(6) NULL,
	DIA7              	smallint(6) NULL,
	DIA8              	smallint(6) NULL,
	DIA9              	smallint(6) NULL,
	DIA10             	smallint(6) NULL,
	DIA11             	smallint(6) NULL,
	DIA12             	smallint(6) NULL,
	DIA13             	smallint(6) NULL,
	DIA14             	smallint(6) NULL,
	DIA15             	smallint(6) NULL,
	DIA16             	smallint(6) NULL,
	DIA17             	smallint(6) NULL,
	DIA18             	smallint(6) NULL,
	DIA19             	smallint(6) NULL,
	DIA20             	smallint(6) NULL,
	DIA21             	smallint(6) NULL,
	DIA22             	smallint(6) NULL,
	DIA23             	smallint(6) NULL,
	DIA24             	smallint(6) NULL,
	DIA25             	smallint(6) NULL,
	DIA26             	smallint(6) NULL,
	DIA27             	smallint(6) NULL,
	DIA28             	smallint(6) NULL,
	DIA29             	smallint(6) NULL,
	DIA30             	smallint(6) NULL,
	DIA31             	smallint(6) NULL,
	DIAS_TRABAJADOS   	smallint(6) NULL,
	ASIS_PROMEDIO     	decimal(10,4) NULL,
	ESTADO_DECLARACION	smallint(6) NULL DEFAULT '0',
	DIAS_ASISTIDOS    	smallint(6) NULL,
	ESTADO_PAGO       	smallint(6) NULL DEFAULT '0',
	FECHA_MATRICULA   	date NULL DEFAULT '1900-01-01',
	ESTADO_COLISION   	smallint(6) NULL DEFAULT '0',
	REGIMEN_SEP       	smallint(6) NULL DEFAULT '0',
	TIPO_ALUMNO       	smallint(6) NULL DEFAULT '0',
	ORDEN_MATRICULA   	smallint(6) NULL DEFAULT '0',
	TIPO_AULA         	smallint(6) NULL DEFAULT '1',
	JECD              	smallint(6) NULL DEFAULT '-100',
	COD_ENS_SUBV      	int(11) NULL DEFAULT '0',
	COD_GRA_SUBV      	int(11) NULL DEFAULT '0',
	MONTO_SUBV_NORMAL 	decimal(20,5) NULL DEFAULT '0.00000',
	PRIMARY KEY(ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
AUTO_INCREMENT = 0
GO


CREATE TABLE sige_asistencia_declarada_sep_poseidon  ( 
	RBD              	int(11) NOT NULL,
	ANIO_ASIST       	smallint(6) NOT NULL,
	MES_ASIST        	smallint(6) NOT NULL,
	ANIO_PAGO        	smallint(6) NOT NULL,
	MES_PAGO         	smallint(6) NOT NULL,
	COD_ENSE         	smallint(6) NOT NULL,
	NIVEL            	smallint(6) NOT NULL,
	ASISTENCIA_MES   	decimal(10,4) NULL,
	MATRICULA_INICIAL	int(11) NOT NULL,
	ALTAS            	int(11) NOT NULL,
	BAJAS            	int(11) NOT NULL,
	MATRICULA_FINAL  	int(11) NOT NULL,
	PRIMARY KEY(RBD,ANIO_ASIST,MES_ASIST,ANIO_PAGO,MES_PAGO,COD_ENSE,NIVEL)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
AUTO_INCREMENT = 0
GO







CREATE TABLE sige_asistencia_declarada_pie  ( 
	MES_PAGO          	smallint(6) NOT NULL,
	MES_ESCOLAR       	smallint(6) NOT NULL,
	RBD               	int(11) NOT NULL,
	COD_ENS           	smallint(6) NOT NULL,
	COD_GRA           	smallint(6) NOT NULL,
	LET_CUR           	varchar(2) NOT NULL,
	ANO_ESCOLAR       	int(11) NOT NULL,
	SAL_RUN           	varchar(20) NOT NULL,
	DIA1              	smallint(6) NULL,
	DIA2              	smallint(6) NULL,
	DIA3              	smallint(6) NULL,
	DIA4              	smallint(6) NULL,
	DIA5              	smallint(6) NULL,
	DIA6              	smallint(6) NULL,
	DIA7              	smallint(6) NULL,
	DIA8              	smallint(6) NULL,
	DIA9              	smallint(6) NULL,
	DIA10             	smallint(6) NULL,
	DIA11             	smallint(6) NULL,
	DIA12             	smallint(6) NULL,
	DIA13             	smallint(6) NULL,
	DIA14             	smallint(6) NULL,
	DIA15             	smallint(6) NULL,
	DIA16             	smallint(6) NULL,
	DIA17             	smallint(6) NULL,
	DIA18             	smallint(6) NULL,
	DIA19             	smallint(6) NULL,
	DIA20             	smallint(6) NULL,
	DIA21             	smallint(6) NULL,
	DIA22             	smallint(6) NULL,
	DIA23             	smallint(6) NULL,
	DIA24             	smallint(6) NULL,
	DIA25             	smallint(6) NULL,
	DIA26             	smallint(6) NULL,
	DIA27             	smallint(6) NULL,
	DIA28             	smallint(6) NULL,
	DIA29             	smallint(6) NULL,
	DIA30             	smallint(6) NULL,
	DIA31             	smallint(6) NULL,
	DIAS_TRABAJADOS   	smallint(6) NULL,
	ASIS_PROMEDIO     	decimal(10,4) NULL,
	ESTADO_DECLARACION	smallint(6) NULL DEFAULT '0',
	DIAS_ASISTIDOS    	smallint(6) NULL,
	ESTADO_PAGO       	smallint(6) NULL DEFAULT '0',
	FECHA_MATRICULA   	date NULL DEFAULT '1900-01-01',
	ESTADO_COLISION   	smallint(6) NULL DEFAULT '0',
	REGIMEN_SEP       	smallint(6) NULL DEFAULT '0',
	TIPO_ALUMNO       	smallint(6) NULL DEFAULT '0',
	ORDEN_MATRICULA   	smallint(6) NULL DEFAULT '0',
	TIPO_AULA         	smallint(6) NULL DEFAULT '1',
	JECD              	smallint(6) NULL DEFAULT '-100',
	COD_ENS_SUBV      	int(11) NULL DEFAULT '0',
	COD_GRA_SUBV      	int(11) NULL DEFAULT '0',
	MONTO_SUBV_NORMAL 	decimal(20,5) NULL DEFAULT '0.00000',
	PRIMARY KEY(ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
AUTO_INCREMENT = 0

go

CREATE TABLE sige_declaracion_asis  ( 
	ANO_ESCOLAR         	INTEGER NOT NULL,
	RBD                 	INTEGER NOT NULL,
	COD_ENS             	INTEGER NOT NULL,
	COD_GRA             	INTEGER NOT NULL,
	LET_CUR             	CHARACTER(2) NOT NULL,
	FECHA_DECLARACION   	DATE ,
	HORA_DECLARACION    	TIME ,
	ESTADO_DECLARACION  	SMALLINT ,
	FECHA_MOD           	DATE ,
	HORA_MOD            	TIME  ,
	MES_DECLARACION     	SMALLINT ,
	N_ALUMNOS           	SMALLINT,
	DIAS_TRABAJADOS     	SMALLINT,
	ASIS_PROMEDIO       	DECIMAL(10,4),
	ID_DECLARACION_CERTI	VARCHAR(27) ,
	HABILITADO_SUBV     	SMALLINT ,
	PRIMARY KEY(ANO_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,FECHA_DECLARACION,HORA_DECLARACION,ESTADO_DECLARACION,ID_DECLARACION_CERTI)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
go


CREATE TABLE sige_declaracion_certi  ( 
	ID                  	VARCHAR(27) NOT NULL,
	ANO_ESCOLAR         	INTEGER NOT NULL,
	FECHA_DECLARACION   	DATE ,
	HORA_DECLARACION    	TIME ,
	ESTADO_DECLARACION  	SMALLINT ,
	RBD                 	INTEGER ,
	MES_DECLARACION     	SMALLINT ,
	ID_DECLARACION_CERTI	VARCHAR(27),
	PRIMARY KEY(ID)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci

go


CREATE TABLE sige_asistencia_declarada_multideficit  ( 
	MES_PAGO          	smallint(6) NOT NULL,
	MES_ESCOLAR       	smallint(6) NOT NULL,
	RBD               	int(11) NOT NULL,
	COD_ENS           	smallint(6) NOT NULL,
	COD_GRA           	smallint(6) NOT NULL,
	LET_CUR           	varchar(2) NOT NULL,
	ANO_ESCOLAR       	int(11) NOT NULL,
	SAL_RUN           	varchar(20) NOT NULL,
	DIA1              	smallint(6) NULL,
	DIA2              	smallint(6) NULL,
	DIA3              	smallint(6) NULL,
	DIA4              	smallint(6) NULL,
	DIA5              	smallint(6) NULL,
	DIA6              	smallint(6) NULL,
	DIA7              	smallint(6) NULL,
	DIA8              	smallint(6) NULL,
	DIA9              	smallint(6) NULL,
	DIA10             	smallint(6) NULL,
	DIA11             	smallint(6) NULL,
	DIA12             	smallint(6) NULL,
	DIA13             	smallint(6) NULL,
	DIA14             	smallint(6) NULL,
	DIA15             	smallint(6) NULL,
	DIA16             	smallint(6) NULL,
	DIA17             	smallint(6) NULL,
	DIA18             	smallint(6) NULL,
	DIA19             	smallint(6) NULL,
	DIA20             	smallint(6) NULL,
	DIA21             	smallint(6) NULL,
	DIA22             	smallint(6) NULL,
	DIA23             	smallint(6) NULL,
	DIA24             	smallint(6) NULL,
	DIA25             	smallint(6) NULL,
	DIA26             	smallint(6) NULL,
	DIA27             	smallint(6) NULL,
	DIA28             	smallint(6) NULL,
	DIA29             	smallint(6) NULL,
	DIA30             	smallint(6) NULL,
	DIA31             	smallint(6) NULL,
	DIAS_TRABAJADOS   	smallint(6) NULL,
	ASIS_PROMEDIO     	decimal(10,4) NULL,
	ESTADO_DECLARACION	smallint(6) NULL DEFAULT '0',
	DIAS_ASISTIDOS    	smallint(6) NULL,
	ESTADO_PAGO       	smallint(6) NULL DEFAULT '0',
	FECHA_MATRICULA   	date NULL DEFAULT '1900-01-01',
	ESTADO_COLISION   	smallint(6) NULL DEFAULT '0',
	REGIMEN_SEP       	smallint(6) NULL DEFAULT '0',
	TIPO_ALUMNO       	smallint(6) NULL DEFAULT '0',
	ORDEN_MATRICULA   	smallint(6) NULL DEFAULT '0',
	TIPO_AULA         	smallint(6) NULL DEFAULT '1',
	JECD              	smallint(6) NULL DEFAULT '-100',
	COD_ENS_SUBV      	int(11) NULL DEFAULT '0',
	COD_GRA_SUBV      	int(11) NULL DEFAULT '0',
	MONTO_SUBV_NORMAL 	decimal(20,5) NULL DEFAULT '0.00000',

	PRIMARY KEY(ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS,COD_GRA,LET_CUR,SAL_RUN)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
GO


CREATE TABLE SIGE_INFORME_PREFERENTES(
    CP_REGION       SMALLINT NOT NULL,
    CP_DEPROV       SMALLINT NOT NULL,
    CP_COMUNA       SMALLINT NOT NULL,
    NOM_COMUNA      varchar(50),
    ANO_ESCOLAR     INTEGER  NOT NULL,
    MES_PAGO        SMALLINT NOT NULL,
    MES_ESCOLAR     SMALLINT NOT NULL,
    RBD             INTEGER NOT NULL,
    NOMBRE_ESTA     VARCHAR(150) ,
    TIPO_DEPENDENCIA    SMALLINT NOT NULL,
    COD_ENS_SUBV    SMALLINT    ,
    COD_GRA_SUBV    SMALLINT,
    JECD            SMALLINT,
    ASIS_PROMEDIO_PRIO      DECIMAL(10,4) DEFAULT 0.0,
    ASIS_PROMEDIO_PREF      DECIMAL(10,4) DEFAULT 0.0,
    NUM_ALUMNOS_PRIO        INTEGER DEFAULT 0,
    NUM_ALUMNOS_PREF        INTEGER DEFAULT 0 ,
    primary key (ANO_ESCOLAR,MES_PAGO,MES_ESCOLAR,RBD,COD_ENS_SUBV,COD_GRA_SUBV,JECD)
)
ENGINE = MyISAM
COLLATE utf8_spanish_ci
go


/*

******************************************************************************************************************
/*      ASISTENCIA DECLARADA DUPLICADA 1
/******************************************************************************************************************

--call sp_carga_asistencia_declarada_duplicada(2014,11,10)

CREATE PROCEDURE sp_carga_asistencia_declarada_duplicada (in pano_escolar int, in pmes_pago int,in pmes_actual int)
NOT DETERMINISTIC
CONTAINS SQL
begin

    declare done int default false;

    declare crs_intmespago 	smallint;
    declare crs_mes_escolar	smallint;
    declare crs_rbd	integer;
    declare crs_cod_ens	smallint;
    declare crs_cod_gra	smallint;
    declare crs_let_cur	varchar(2);
    declare crs_ano_escolar	integer;
    declare crs_sal_run	varchar(20);
    declare crs_dia1	smallint;
    declare crs_dia2	smallint;
    declare crs_dia3	smallint;
    declare crs_dia4	smallint;
    declare crs_dia5	smallint;
    declare crs_dia6	smallint;
    declare crs_dia7	smallint;
    declare crs_dia8	smallint;
    declare crs_dia9	smallint;
    declare crs_dia10	smallint;
    declare crs_dia11	smallint;
    declare crs_dia12	smallint;
    declare crs_dia13	smallint;
    declare crs_dia14	smallint;
    declare crs_dia15	smallint;
    declare crs_dia16	smallint;
    declare crs_dia17	smallint;
    declare crs_dia18	smallint;
    declare crs_dia19	smallint;
    declare crs_dia20	smallint;
    declare crs_dia21	smallint;
    declare crs_dia22	smallint;
    declare crs_dia23	smallint;
    declare crs_dia24	smallint;
    declare crs_dia25	smallint;
    declare crs_dia26	smallint;
    declare crs_dia27	smallint;
    declare crs_dia28	smallint;
    declare crs_dia29 	smallint;
    declare crs_dia30	smallint;
    declare crs_dia31	smallint;
    declare crs_dias_trabajados	smallint;
    declare crs_asis_promedio	decimal(10,4);
    declare crs_estado_declaracion	smallint;
    declare crs_dias_asistidos	smallint;
    declare crs_fecha_incorporacion	date;
    declare crs_estado_colision	smallint;
    declare crs_estado_pago	smallint;
    declare crs_contador	integer default 0;
    declare crs_regimen_sep integer;
    declare crs_tipo_alumno integer;
    declare crs_orden_matricula integer;
    declare crs_curso_actual	varchar(30) default '';
    declare crs_curso_aux		varchar(30) default '';
    declare crs_exe smallint;
    declare crs_tipo_aula smallint;
    declare vintalumno_retirado smallint;
    declare vintasistencia_duplicada smallint;
    declare vdiastrabajados_duplicado varchar(250) default '';
    declare crs_aplica_jecd smallint default 0;
    declare crs_cod_ens_subv smallint default 0;
    declare crs_cod_gra_subv smallint default 0;
    declare count_cursor integer default 0 ;
    declare ptotal_asis integer default 0 ;
    declare vfacuse decimal(7,5) default 0 ;
    declare vvaloruse decimal(10,4) default 0 ;
    declare vmonto_subv_normal decimal(10,4) default 0 ;
    declare vdiastrabajados_duplicado_palabra varchar(4000) default '';
    declare vexistenrundup integer default 0 ;


    


    select count(*) into @existe
    from sige_run_duplicada where ano_escolar = pano_escolar and mes_pago = pmes_pago;


    if(@existe = 0) then
            insert into sige_run_duplicada
            select  pano_escolar    ano_escolar,
                    pmes_pago       mes_pago,
                    sal_run 
            from sige_matricula sm, sige_establecimiento se
            where sm.ano_escolar = pano_escolar
            and sm.rbd = se.rbd
            and se.tipo_dependencia in (1,2,3,5)
            group by sal_run
            having count(*) > 1;

    end if;

   

    insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)        
    select pano_escolar ano_escolar, pmes_pago mes_pago, pmes_actual mes_escolar,concat('Matricula duplicada [',pano_escolar,',',pmes_pago,']:',cast(count(*) as char)) as descripcion
    from    sige_run_duplicada
    where   ano_escolar = pano_escolar and
                mes_pago    = pmes_pago;



     delete from sige_run_duplicada_asistencia
     where ano_escolar      = pano_escolar
           and mes_pago     = pmes_pago
           and mes_escolar  = pmes_actual;
        
        insert into sige_run_duplicada_asistencia   
        select sa.mes_pago,sa.mes_escolar,sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur , sa.ano_escolar, sa.sal_run , sa.dia1, sa.dia2 ,  sa.dia3, sa.dia4,sa.dia5 , sa.dia6 , sa.dia7 ,sa.dia8 ,  sa.dia9 , sa.dia10, sa.dia11 , sa.dia12, sa.dia13 , sa.dia14 ,sa.dia15,sa.dia16 ,  sa.dia17 ,  sa.dia18 ,  sa.dia19, sa.dia20 ,  sa.dia21,  sa.dia22 ,  sa.dia23, sa.dia24 ,  sa.dia25 , sa.dia26 ,  sa.dia27  , sa.dia28 , sa.dia29  ,  sa.dia30 , sa.dia31 ,  sa.dias_trabajados , sa.asis_promedio ,  sa.estado_declaracion  ,  sa.dias_asistidos, sa.fecha_matricula, sa.regimen_sep,sa.tipo_alumno,sa.orden_matricula,sa.tipo_aula,sa.jecd,sa.cod_ens_subv,sa.cod_gra_subv, sa.monto_subv_normal
        from sige_asistencia_declarada sa, sige_run_duplicada sd
        where   sa.ano_escolar          = pano_escolar
                and sa.mes_escolar      = pmes_actual
                and sa.mes_pago         = pmes_pago
                and sa.mes_pago         = sd.mes_pago
                and sa.sal_run          = sd.sal_run 
                and sa.estado_declaracion in (3,2)
                and sa.habilitado_subv  = 1
                and sd.ano_escolar = sa.ano_escolar
               
        order by sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur, sa.orden_matricula;
    

  
    insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)        
    select   pano_escolar ano_escolar, pmes_pago mes_pago, pmes_actual mes_escolar,concat('Matricula Duplicada Asistencia [',pano_escolar,',',pmes_pago,']:',cast(count(*) as char)) as descripcion
        from sige_run_duplicada_asistencia
        where ano_escolar       = pano_escolar
              and mes_pago      = pmes_pago
              and mes_escolar   = pmes_actual;
    

        update sige_run_duplicada_asistencia A,
        (
            select sal_run
            from sige_run_duplicada_asistencia
            where   ANO_ESCOLAR     = pano_escolar 
                    and MES_PAGO    = pmes_pago 
                    and MES_ESCOLAR = pmes_actual 
            group by sal_run
            having  sum(IF(DIA1=1,1,IF(DIA1=2,1,0))) > 1 or
                    sum(IF(DIA2=1,1,IF(DIA2=2,1,0))) > 1 or
                    sum(IF(DIA3=1,1,IF(DIA3=2,1,0))) > 1 or
                    sum(IF(DIA4=1,1,IF(DIA4=2,1,0))) > 1 or
                    sum(IF(DIA5=1,1,IF(DIA5=2,1,0))) > 1 or
                    sum(IF(DIA6=1,1,IF(DIA6=2,1,0))) > 1 or
                    sum(IF(DIA7=1,1,IF(DIA7=2,1,0))) > 1 or
                    sum(IF(DIA8=1,1,IF(DIA8=2,1,0))) > 1 or
                    sum(IF(DIA9=1,1,IF(DIA9=2,1,0))) > 1 or
                    sum(IF(DIA10=1,1,IF(DIA10=2,1,0))) > 1 or
                    sum(IF(DIA11=1,1,IF(DIA11=2,1,0))) > 1 or
                    sum(IF(DIA12=1,1,IF(DIA12=2,1,0))) > 1 or
                    sum(IF(DIA13=1,1,IF(DIA13=2,1,0))) > 1 or
                    sum(IF(DIA14=1,1,IF(DIA14=2,1,0))) > 1 or
                    sum(IF(DIA15=1,1,IF(DIA15=2,1,0))) > 1 or
                    sum(IF(DIA16=1,1,IF(DIA16=2,1,0))) > 1 or
                    sum(IF(DIA17=1,1,IF(DIA17=2,1,0))) > 1 or
                    sum(IF(DIA18=1,1,IF(DIA18=2,1,0))) > 1 or
                    sum(IF(DIA19=1,1,IF(DIA19=2,1,0))) > 1 or
                    sum(IF(DIA20=1,1,IF(DIA20=2,1,0))) > 1 or
                    sum(IF(DIA21=1,1,IF(DIA21=2,1,0))) > 1 or
                    sum(IF(DIA22=1,1,IF(DIA22=2,1,0))) > 1 or
                    sum(IF(DIA23=1,1,IF(DIA23=2,1,0))) > 1 or
                    sum(IF(DIA24=1,1,IF(DIA24=2,1,0))) > 1 or
                    sum(IF(DIA25=1,1,IF(DIA25=2,1,0))) > 1 or
                    sum(IF(DIA26=1,1,IF(DIA26=2,1,0))) > 1 or
                    sum(IF(DIA27=1,1,IF(DIA27=2,1,0))) > 1 or
                    sum(IF(DIA28=1,1,IF(DIA28=2,1,0))) > 1 or
                    sum(IF(DIA29=1,1,IF(DIA29=2,1,0))) > 1 or
                    sum(IF(DIA30=1,1,IF(DIA30=2,1,0))) > 1 or
                    sum(IF(DIA31=1,1,IF(DIA31=2,1,0))) > 1
        ) B
        set A.ESTADO_DECLARACION = 99
        where A.SAL_RUN = B.SAL_RUN and
              A.ANO_ESCOLAR = pano_escolar AND
              A.MES_PAGO    = pmes_pago  AND 
              A.MES_ESCOLAR = pmes_actual;




 




end
GO

/******************************************************************************************************************
/*      ASISTENCIA DECLARADA DUPLICADA 2
/******************************************************************************************************************

call sp_carga_asistencia_declarada_duplicada2(2015,4,3)
go
--drop PROCEDURE sp_carga_asistencia_declarada_duplicada2



CREATE PROCEDURE sp_carga_asistencia_declarada_duplicada2(in pano_escolar int, in pmes_pago int,in pmes_actual int)
NOT DETERMINISTIC
CONTAINS SQL
begin

    declare done int default false;

    declare crs_intmespago 	smallint;
    declare crs_mes_escolar	smallint;
    declare crs_rbd	integer;
    declare crs_cod_ens	smallint;
    declare crs_cod_gra	smallint;
    declare crs_let_cur	varchar(2) CHARSET utf8 COLLATE utf8_spanish_ci ;
    declare crs_ano_escolar	integer;
    declare crs_sal_run	varchar(20) CHARSET utf8 COLLATE utf8_spanish_ci ;
    declare crs_dia1	smallint;
    declare crs_dia2	smallint;
    declare crs_dia3	smallint;
    declare crs_dia4	smallint;
    declare crs_dia5	smallint;
    declare crs_dia6	smallint;
    declare crs_dia7	smallint;
    declare crs_dia8	smallint;
    declare crs_dia9	smallint;
    declare crs_dia10	smallint;
    declare crs_dia11	smallint;
    declare crs_dia12	smallint;
    declare crs_dia13	smallint;
    declare crs_dia14	smallint;
    declare crs_dia15	smallint;
    declare crs_dia16	smallint;
    declare crs_dia17	smallint;
    declare crs_dia18	smallint;
    declare crs_dia19	smallint;
    declare crs_dia20	smallint;
    declare crs_dia21	smallint;
    declare crs_dia22	smallint;
    declare crs_dia23	smallint;
    declare crs_dia24	smallint;
    declare crs_dia25	smallint;
    declare crs_dia26	smallint;
    declare crs_dia27	smallint;
    declare crs_dia28	smallint;
    declare crs_dia29 	smallint;
    declare crs_dia30	smallint;
    declare crs_dia31	smallint;
    declare crs_dias_trabajados	smallint;
    declare crs_asis_promedio	decimal(10,4);
    declare crs_estado_declaracion	smallint;
    declare crs_dias_asistidos	smallint;
    declare crs_fecha_incorporacion	date;
    declare crs_estado_colision	smallint;
    declare crs_estado_pago	smallint;
    declare crs_contador	integer default 0;
    declare crs_regimen_sep integer;
    declare crs_tipo_alumno integer;
    declare crs_orden_matricula integer;
    declare crs_curso_actual	varchar(30) default '';
    declare crs_curso_aux		varchar(30) default '';
    declare crs_exe smallint;
    declare crs_tipo_aula smallint;
    declare vintalumno_retirado smallint;
    declare vintasistencia_duplicada smallint;
    declare vdiastrabajados_duplicado varchar(250) default '';
    declare crs_aplica_jecd smallint default 0;
    declare crs_cod_ens_subv smallint default 0;
    declare crs_cod_gra_subv smallint default 0;
    declare count_cursor integer default 0 ;
    declare ptotal_asis integer default 0 ;
    declare vfacuse decimal(7,5) default 0 ;
    declare vvaloruse decimal(10,4) default 0 ;
    declare vmonto_subv_normal decimal(10,4) default 0 ;
    declare vdiastrabajados_duplicado_palabra varchar(4000) default '';
    declare vexistenrundup integer default 0 ;



    

    
    declare duplicados cursor for
                  select sa.mes_escolar,sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur , sa.ano_escolar, sa.sal_run , sa.dia1, sa.dia2 ,  sa.dia3, sa.dia4,sa.dia5 , sa.dia6 , sa.dia7 ,sa.dia8 ,  sa.dia9 , sa.dia10, sa.dia11,sa.dia12, sa.dia13 , sa.dia14 ,sa.dia15,sa.dia16 ,  sa.dia17 ,  sa.dia18 ,  sa.dia19, sa.dia20 ,  sa.dia21,  sa.dia22 ,  sa.dia23, sa.dia24 ,  sa.dia25 , sa.dia26 ,  sa.dia27  , sa.dia28 , sa.dia29,sa.dia30 , sa.dia31 ,  sa.dias_trabajados , sa.asis_promedio ,  sa.estado_declaracion  ,  sa.dias_asistidos, sa.fecha_matricula, sa.regimen_sep,sa.tipo_alumno,sa.orden_matricula,sa.tipo_aula,sa.jecd,sa.cod_ens_subv,sa.cod_gra_subv, sa.monto_subv_normal
            from sige_run_duplicada_asistencia sa
            where sa.ano_escolar            = pano_escolar 
			      and sa.mes_escolar        = pmes_actual
                  and sa.mes_pago           = pmes_pago
                  and sa.estado_declaracion = 99
                  --and sa.rbd                = 1
            order by sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur, sa.orden_matricula;

declare continue handler for not found set done = true; 




      open duplicados;
        read_loop_1:loop
                fetch duplicados into  crs_mes_escolar,crs_rbd, crs_cod_ens,crs_cod_gra, crs_let_cur , crs_ano_escolar, crs_sal_run , crs_dia1, crs_dia2 ,  crs_dia3, crs_dia4,crs_dia5 , crs_dia6 , crs_dia7 ,crs_dia8 ,  crs_dia9 , crs_dia10,crs_dia11 , crs_dia12, crs_dia13 , crs_dia14 ,crs_dia15,crs_dia16 ,  crs_dia17 ,  crs_dia18 ,  crs_dia19, crs_dia20 ,  crs_dia21,  crs_dia22 ,  crs_dia23, crs_dia24 ,  crs_dia25 , crs_dia26 ,  crs_dia27, crs_dia28 , crs_dia29  ,  crs_dia30 , crs_dia31 ,  crs_dias_trabajados , crs_asis_promedio ,  crs_estado_declaracion  ,  crs_dias_asistidos,crs_fecha_incorporacion, crs_regimen_sep,crs_tipo_alumno,crs_orden_matricula,crs_tipo_aula,crs_aplica_jecd,crs_cod_ens_subv,crs_cod_gra_subv,vmonto_subv_normal; 
                if done then
                    leave read_loop_1;
                end if;

                set vintalumno_retirado = if(crs_dia1=1,1,0)+ if(crs_dia2=1,1,0)+ if(crs_dia3=1,1,0)+ if(crs_dia4=1,1,0)+ if(crs_dia5=1,1,0)+ if(crs_dia6=1,1,0)+ if(crs_dia7=1,1,0)+ if(crs_dia8=1,1,0)+ if(crs_dia9=1,1,0)+ if(crs_dia10=1,1,0)+ if(crs_dia11=1,1,0)+ if(crs_dia12=1,1,0)+ if(crs_dia13=1,1,0)+ if(crs_dia14=1,1,0)+ if(crs_dia15=1,1,0)+ if(crs_dia16=1,1,0)+ if(crs_dia17=1,1,0)+ if(crs_dia18=1,1,0)+ if(crs_dia19=1,1,0)+ if(crs_dia20=1,1,0)+ if(crs_dia21=1,1,0)+ if(crs_dia22=1,1,0)+ if(crs_dia23=1,1,0)+ if(crs_dia24=1,1,0)+ if(crs_dia25=1,1,0)+ if(crs_dia26=1,1,0)+ if(crs_dia27=1,1,0)+ if(crs_dia28=1,1,0)+ if(crs_dia29=1,1,0)+ if(crs_dia30=1,1,0)+ if(crs_dia31=1,1,0);  


                set vintasistencia_duplicada = 0;


                if vintalumno_retirado > 0 then 
                    select if((if(crs_dia1=1,if(sum(D.dia1)>0,1,0),0)+ if(crs_dia2=1,if(sum(D.dia2)>0,1,0),0)+ if(crs_dia3=1,if(sum(D.dia3)>0,1,0),0)+ if(crs_dia4=1,if(sum(D.dia4)>0,1,0),0)+ if(crs_dia5=1,if(sum(D.dia5)>0,1,0),0)+ if(crs_dia6=1,if(sum(D.dia6)>0,1,0),0)+ if(crs_dia7=1,if(sum(D.dia7)>0,1,0),0)+ if(crs_dia8=1,if(sum(D.dia8)>0,1,0),0)+ if(crs_dia9=1,if(sum(D.dia9)>0,1,0),0)+ if(crs_dia10=1,if(sum(D.dia10)>0,1,0),0)+ if(crs_dia11=1,if(sum(D.dia11)>0,1,0),0)+ if(crs_dia12=1,if(sum(D.dia12)>0,1,0),0)+ if(crs_dia13=1,if(sum(D.dia13)>0,1,0),0)+ if(crs_dia14=1,if(sum(D.dia14)>0,1,0),0)+ if(crs_dia15=1,if(sum(D.dia15)>0,1,0),0)+ if(crs_dia16=1,if(sum(D.dia16)>0,1,0),0)+ if(crs_dia17=1,if(sum(D.dia17)>0,1,0),0)+ if(crs_dia18=1,if(sum(D.dia18)>0,1,0),0)+ if(crs_dia19=1,if(sum(D.dia19)>0,1,0),0)+ if(crs_dia20=1,if(sum(D.dia20)>0,1,0),0)+ if(crs_dia21=1,if(sum(D.dia21)>0,1,0),0)+ if(crs_dia22=1,if(sum(dia22)>0,1,0),0)+ if(crs_dia23=1,if(sum(D.dia23)>0,1,0),0)+ if(crs_dia24=1,if(sum(D.dia24)>0,1,0),0)+ if(crs_dia25=1,if(sum(D.dia25)>0,1,0),0)+ if(crs_dia26=1,if(sum(D.dia26)>0,1,0),0)+ if(crs_dia27=1,if(sum(D.dia27)>0,1,0),0)+ if(crs_dia28=1,if(sum(D.dia28)>0,1,0),0)+ if(crs_dia29=1,if(sum(D.dia29)>0,1,0),0)+ if(crs_dia30=1,if(sum(D.dia30)>0,1,0),0)+ if(crs_dia31=1,if(sum(D.dia31)>0,1,0),0))>0,1,0) colision
                    into vintasistencia_duplicada
                    from
                       (select if(A.dia1=1,1,0) dia1,  if(A.dia2=1,1,0) dia2, if(A.dia3=1,1,0) dia3, if(A.dia4=1,1,0) dia4, if(A.dia5=1,1,0) dia5, if(A.dia6=1,1,0) dia6, if(A.dia7=1,1,0) dia7, if(A.dia8=1,1,0) dia8, if(A.dia9=1,1,0) dia9, if(A.dia10=1,1,0) dia10, if(A.dia11=1,1,0) dia11, if(A.dia12=1,1,0) dia12, if(A.dia13=1,1,0) dia13, if(A.dia14=1,1,0) dia14, if(A.dia15=1,1,0) dia15, if(A.dia16=1,1,0) dia16, if(A.dia17=1,1,0) dia17, if(A.dia18=1,1,0) dia18, if(A.dia19=1,1,0) dia19, if(A.dia20=1,1,0) dia20, if(A.dia21=1,1,0) dia21, if(A.dia22=1,1,0) dia22, if(A.dia23=1,1,0) dia23, if(A.dia24=1,1,0) dia24, if(A.dia25=1,1,0) dia25, if(A.dia26=1,1,0) dia26, if(A.dia27=1,1,0) dia27, if(A.dia28=1,1,0) dia28, if(A.dia29=1,1,0) dia29, if(A.dia30=1,1,0) dia30,if(A.dia31=1,1,0) dia31
                        from sige_run_duplicada_asistencia A
                        where A.ano_escolar  = pano_escolar and
                            A.mes_escolar  = pmes_actual and
                            A.mes_pago     = pmes_pago and
                            A.sal_run      = crs_sal_run and
                            A.estado_declaracion = 99 and
                            A.rbd <> crs_rbd
                        ) D;


                end if;  


                       

                if vintasistencia_duplicada > 0 then

                SET lc_time_names = 'es_UY';

                 --    insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)
                 --    values (2014,4,3,concat('inserto datos en sige_asistencia_duplicada del rbd-run:',crs_rbd,'-',crs_sal_run));

                     select   concat(if(crs_dia1=1,if(sum(D.dia1)>0,'dia1,',''),'')
                            , if(crs_dia2=1,if(sum(D.dia2)>0,'dia2,',''),'')
                            , if(crs_dia3=1,if(sum(D.dia3)>0,'dia3,',''),'')
                            , if(crs_dia4=1,if(sum(D.dia4)>0,'dia4,',''),'')
                            , if(crs_dia5=1,if(sum(D.dia5)>0,'dia5,',''),'')
                            , if(crs_dia6=1,if(sum(D.dia6)>0,'dia6,',''),'')
                            , if(crs_dia7=1,if(sum(D.dia7)>0,'dia7,',''),'')
                            , if(crs_dia8=1,if(sum(D.dia8)>0,'dia8,',''),'')
                            , if(crs_dia9=1,if(sum(D.dia9)>0,'dia9,',''),'')
                            , if(crs_dia10=1,if(sum(D.dia10)>0,'dia10,',''),'')
                            , if(crs_dia11=1,if(sum(D.dia11)>0,'dia11,',''),'')
                            , if(crs_dia12=1,if(sum(D.dia12)>0,'dia12,',''),'')
                            , if(crs_dia13=1,if(sum(D.dia13)>0,'dia13,',''),'')
                            , if(crs_dia14=1,if(sum(D.dia14)>0,'dia14,',''),'')
                            , if(crs_dia15=1,if(sum(D.dia15)>0,'dia15,',''),'')
                            , if(crs_dia16=1,if(sum(D.dia16)>0,'dia16,',''),'')
                            , if(crs_dia17=1,if(sum(D.dia17)>0,'dia17,',''),'')
                            , if(crs_dia18=1,if(sum(D.dia18)>0,'dia18,',''),'')
                            , if(crs_dia19=1,if(sum(D.dia19)>0,'dia19,',''),'')
                            , if(crs_dia20=1,if(sum(D.dia20)>0,'dia20,',''),'')
                            , if(crs_dia21=1,if(sum(D.dia21)>0,'dia21,',''),'')
                            , if(crs_dia22=1,if(sum(dia22)>0,'dia22,',''),'')
                            , if(crs_dia23=1,if(sum(D.dia23)>0,'dia23,',''),'')
                            , if(crs_dia24=1,if(sum(D.dia24)>0,'dia24,',''),'')
                            , if(crs_dia25=1,if(sum(D.dia25)>0,'dia25,',''),'')
                            , if(crs_dia26=1,if(sum(D.dia26)>0,'dia26,',''),'')
                            , if(crs_dia27=1,if(sum(D.dia27)>0,'dia27,',''),'')
                            , if(crs_dia28=1,if(sum(D.dia28)>0,'dia28,',''),'')
                            , if(crs_dia29=1,if(sum(D.dia29)>0,'dia29,',''),'')
                            , if(crs_dia30=1,if(sum(D.dia30)>0,'dia30,',''),'')
                            , if(crs_dia31=1,if(sum(D.dia31)>0,'dia31',''),'')) dias,
                       concat(if(crs_dia1=1,if(sum(D.dia1)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-01')),' 1,'),''),'')
                            , if(crs_dia2=1,if(sum(D.dia2)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-02')),' 2,'),''),'')
                            , if(crs_dia3=1,if(sum(D.dia3)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-03')),' 3,'),''),'')
                            , if(crs_dia4=1,if(sum(D.dia4)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-04')),' 4,'),''),'')
                            , if(crs_dia5=1,if(sum(D.dia5)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-05')),' 5,'),''),'')
                            , if(crs_dia6=1,if(sum(D.dia6)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-06')),' 6,'),''),'')
                            , if(crs_dia7=1,if(sum(D.dia7)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-07')),' 7,'),''),'')
                            , if(crs_dia8=1,if(sum(D.dia8)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-08')),' 8,'),''),'')
                            , if(crs_dia9=1,if(sum(D.dia9)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-09')),' 9,'),''),'')
                            , if(crs_dia10=1,if(sum(D.dia10)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-10')),' 10,'),''),'')
                            , if(crs_dia11=1,if(sum(D.dia11)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-11')),' 11,'),''),'')
                            , if(crs_dia12=1,if(sum(D.dia12)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-12')),' 12,'),''),'')
                            , if(crs_dia13=1,if(sum(D.dia13)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-13')),' 13,'),''),'')
                            , if(crs_dia14=1,if(sum(D.dia14)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-14')),' 14,'),''),'')
                            , if(crs_dia15=1,if(sum(D.dia15)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-15')),' 15,'),''),'')
                            , if(crs_dia16=1,if(sum(D.dia16)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-16')),' 16,'),''),'')
                            , if(crs_dia17=1,if(sum(D.dia17)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-17')),' 17,'),''),'')
                            , if(crs_dia18=1,if(sum(D.dia18)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-18')),' 18,'),''),'')
                            , if(crs_dia19=1,if(sum(D.dia19)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-19')),' 19,'),''),'')
                            , if(crs_dia20=1,if(sum(D.dia20)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-20')),' 20,'),''),'')
                            , if(crs_dia21=1,if(sum(D.dia21)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-21')),' 21,'),''),'')
                            , if(crs_dia22=1,if(sum(D.dia22)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-22')),' 22,'),''),'')
                            , if(crs_dia23=1,if(sum(D.dia23)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-23')),' 23,'),''),'')
                            , if(crs_dia24=1,if(sum(D.dia24)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-24')),' 24,'),''),'')
                            , if(crs_dia25=1,if(sum(D.dia25)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-25')),' 25,'),''),'')
                            , if(crs_dia26=1,if(sum(D.dia26)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-26')),' 26,'),''),'')
                            , if(crs_dia27=1,if(sum(D.dia27)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-27')),' 27,'),''),'')
                            , if(crs_dia28=1,if(sum(D.dia28)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-28')),' 28,'),''),'')
                            , if(crs_dia29=1,if(sum(D.dia29)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-29')),' 29,'),''),'')
                            , if(crs_dia30=1,if(sum(D.dia30)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-30')),' 30,'),''),'')
                            , if(crs_dia31=1,if(sum(D.dia31)>0,concat(dayname(concat(cast(pano_escolar AS CHAR(4)),'-',cast(pmes_actual as char(2)),'-31')),' 31,'),''),'')) dias_palabra
                    into vdiastrabajados_duplicado,vdiastrabajados_duplicado_palabra
                    from
                       (select if(A.dia1=1,1,0) dia1,  if(A.dia2=1,1,0) dia2, if(A.dia3=1,1,0) dia3, if(A.dia4=1,1,0) dia4, if(A.dia5=1,1,0) dia5, if(A.dia6=1,1,0) dia6, if(A.dia7=1,1,0) dia7, if(A.dia8=1,1,0) dia8, if(A.dia9=1,1,0) dia9, if(A.dia10=1,1,0) dia10, if(A.dia11=1,1,0) dia11, if(A.dia12=1,1,0) dia12, if(A.dia13=1,1,0) dia13, if(A.dia14=1,1,0) dia14, if(A.dia15=1,1,0) dia15, if(A.dia16=1,1,0) dia16, if(A.dia17=1,1,0) dia17, if(A.dia18=1,1,0) dia18, if(A.dia19=1,1,0) dia19, if(A.dia20=1,1,0) dia20, if(A.dia21=1,1,0) dia21, if(A.dia22=1,1,0) dia22, if(A.dia23=1,1,0) dia23, if(A.dia24=1,1,0) dia24, if(A.dia25=1,1,0) dia25, if(A.dia26=1,1,0) dia26, if(A.dia27=1,1,0) dia27, if(A.dia28=1,1,0) dia28, if(A.dia29=1,1,0) dia29, if(A.dia30=1,1,0) dia30,if(A.dia31=1,1,0) dia31
                        from sige_run_duplicada_asistencia A
                        where A.ano_escolar  = pano_escolar and
                            A.mes_escolar  = pmes_actual and
                            A.mes_pago     = pmes_pago and
                            A.sal_run      = crs_sal_run and
                            A.estado_declaracion = 99 and
                            A.rbd <> crs_rbd
                        ) D;



                    insert into sige_asistencia_duplicada(id, ano_escolar,mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur, sal_run, dias_trabajados, asis_promedio, estado_declaracion, dias_asistidos, estado,dias_trabajados_palabra )
                    select uuid(),crs_ano_escolar,pmes_pago,crs_mes_escolar,crs_rbd,crs_cod_ens,crs_cod_gra, crs_let_cur,crs_sal_run,vdiastrabajados_duplicado,crs_asis_promedio,crs_estado_declaracion,crs_dias_asistidos,1,vdiastrabajados_duplicado_palabra;
                    

                    update sige_asistencia_declarada 
					set estado_pago = 3, 
                        estado_colision = vintasistencia_duplicada
					where ano_escolar = crs_ano_escolar
					and mes_pago = pmes_pago
					and mes_escolar = pmes_actual
					and rbd = crs_rbd
					and cod_ens = crs_cod_ens
					and cod_gra =crs_cod_gra
					and let_cur = crs_let_cur
					and sal_run = crs_sal_run
                    and estado_pago <> 4;

                else
                    set vintasistencia_duplicada = 0;
                end if;

       

        end loop;
      close duplicados;



end
GO







/******************************************************************************************************************
/*      ORDENA LISTA CURSO PARA CURSOS CON MÀS DE 45 ALUMNOS
/******************************************************************************************************************

call sp_ordena_lista_curso_asistencia_declarada(2014,8,3,999999)
go
--drop PROCEDURE sp_ordena_lista_curso_asistencia_declarada
--go

CREATE PROCEDURE `sp_ordena_lista_curso_asistencia_declarada` (in pano_escolar int, in pmes_pago int,in pmes_actual int,in prbd int)
NOT DETERMINISTIC
CONTAINS SQL
begin



	declare v_ano_escolar,v_mes_pago,v_mes_escolar,v_rbd,v_cod_ens,v_cod_gra int;
	declare v_let_cur varchar(2) CHARSET utf8 COLLATE utf8_spanish_ci ;
	declare done int default false;


    
    
    declare cursos45  cursor for
			select ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur
			    from sige_asistencia_declarada 
			    where ano_escolar 	= pano_escolar
			    and mes_pago 		= pmes_pago
			    and mes_escolar 	= pmes_actual
                and (rbd = prbd or prbd = 0)                
			    group by ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur
			    having count(*)>45 or
                       (count(*) <= 45 and max(orden_matricula)>45);
		declare continue handler for not found set done = true;


        delete from  tmp_ordena_lista;
       
      
		open cursos45;
		read_loop_1: loop
				fetch cursos45 into v_ano_escolar,v_mes_pago,v_mes_escolar,v_rbd,v_cod_ens,v_cod_gra,v_let_cur; 
					if done then
						leave read_loop_1;
					end if;


					
                    insert into tmp_ordena_lista
					select sad.ano_escolar,sad.mes_pago,sad.mes_escolar,sad.rbd,sad.cod_ens,sad.cod_gra,sad.let_cur,sad.sal_run ,sad.orden_matricula, @row_number := @row_number + 1 orden_final
                        from sige_asistencia_declarada sad ,  (select @row_number:=0) R
                        where sad.ano_escolar = v_ano_escolar
                        and sad.mes_pago = v_mes_pago
                        and sad.mes_escolar = v_mes_escolar
                        and sad.rbd = v_rbd
                        and sad.cod_ens = v_cod_ens
                        and sad.cod_gra = v_cod_gra
                        and sad.let_cur = v_let_cur
                        order by sad.ano_escolar,sad.mes_pago,sad.mes_escolar,sad.rbd,sad.cod_ens,sad.cod_gra,sad.let_cur, sad.orden_matricula asc;

                     end loop read_loop_1;
        close cursos45;

        OPTIMIZE TABLE tmp_ordena_lista;

        update  sige_asistencia_declarada s, tmp_ordena_lista t
        set     s.orden_matricula = t.orden_final,
                s.estado_pago = if(t.orden_final > 45,2,1)
        where   s.ano_escolar = t.ano_escolar and
                s.mes_pago    = t.mes_pago and
                s.mes_escolar = t.mes_escolar and
                s.rbd         = t.rbd and
                s.cod_ens     = t.cod_ens and
                s.cod_gra     = t.cod_gra and
                s.let_cur     = t.let_cur and
                s.sal_run     = t.sal_run and
                s.estado_pago <> 4;


        insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)        
        select pano_escolar ano_escolar, pmes_pago mes_pago, pmes_actual mes_escolar,concat('N? de registros procesados:',cast(count(*) as char)) as descripcion
        from tmp_ordena_lista;

end





/******************************************************************************************************************
/*      EXCEDENTE DÍA. CURSOS CON ASISTENCIA > 45, SET ESTADO_PAGO = 1 (CURSO COMPLETO, NO CONSIDERA RUN CON ESTADO_PAGO = 4)
/******************************************************************************************************************

--call sp_proceso_asistencia_excedente_dia(2014,11,10,0)

CREATE PROCEDURE sp_proceso_asistencia_excedente_dia (in pano_escolar int, in pmes_pago int,in pmes_actual int,in prbd int)
NOT DETERMINISTIC
CONTAINS SQL
begin

	drop table if exists temp1;
        create temporary table temp1 engine=memory as(
            select  distinct ano_escolar, mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur 
            from sige_asistencia_declarada
            where ano_escolar = pano_escolar 
            and   mes_pago    = pmes_pago
            and   mes_escolar = pmes_actual
            and   estado_pago = 2
            and   habilitado_subv = 1
            and   estado_declaracion in (3,2)
            and (rbd = prbd or prbd = 0)
            
        );
        
        create index  idx_tmp on temp1(ano_escolar, mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur);

        insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)        
        select pano_escolar ano_escolar, pmes_pago mes_pago, pmes_actual mes_escolar,concat('N? de cursos con estado_pago(2):',cast(count(*) as char)) as descripcion
        from temp1;

        drop table if exists temp2;
        create temporary table temp2 engine=memory as(
            select a.ano_escolar,a.mes_pago,a.mes_escolar,a.rbd,a.cod_ens,a.cod_gra,a.let_cur
            from sige_asistencia_declarada a, temp1 b
            where     a.ano_escolar = b.ano_escolar
                and   a.mes_pago    = b.mes_pago
                and   a.mes_escolar = b.mes_escolar
                and   a.rbd         = b.rbd
                and   a.cod_ens     = b.cod_ens
                and   a.cod_gra     = b.cod_gra
                and   a.let_cur     = b.let_cur
                and   a.estado_pago <> 4
                and   a.habilitado_subv = 1
                and   a.estado_declaracion in (3,2)
            group by a.mes_pago,a.mes_escolar,a.rbd,a.cod_ens,a.cod_gra,a.let_cur
            having  sign(1+sign(((sum(if(a.dia1=1,1,if(a.dia1=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia2=1,1,if(a.dia2=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia3=1,1,if(a.dia3=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia4=1,1,if(a.dia4=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia5=1,1,if(a.dia5=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia6=1,1,if(a.dia6=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia7=1,1,if(a.dia7=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia8=1,1,if(a.dia8=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia9=1,1,if(a.dia9=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia10=1,1,if(a.dia10=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia11=1,1,if(a.dia11=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia12=1,1,if(a.dia12=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia13=1,1,if(a.dia13=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia14=1,1,if(a.dia14=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia15=1,1,if(a.dia15=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia16=1,1,if(a.dia16=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia17=1,1,if(a.dia17=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia18=1,1,if(a.dia18=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia19=1,1,if(a.dia19=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia20=1,1,if(a.dia20=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia21=1,1,if(a.dia21=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia22=1,1,if(a.dia22=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia23=1,1,if(a.dia23=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia24=1,1,if(a.dia24=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia25=1,1,if(a.dia25=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia26=1,1,if(a.dia26=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia27=1,1,if(a.dia27=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia28=1,1,if(a.dia28=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia29=1,1,if(a.dia29=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia30=1,1,if(a.dia30=2,1,0))))-46)))+
                    sign(1+sign(((sum(if(a.dia31=1,1,if(a.dia31=2,1,0))))-46))) = 0

        );

         create index  idx_t on temp2(ano_escolar,mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur);


        insert into proceso(ano_escolar,mes_pago,mes_escolar,descripcion)        
        select pano_escolar ano_escolar, pmes_pago mes_pago, pmes_actual mes_escolar,concat('Nº de cursos sin excedente:',cast(count(*) as char)) as descripcion
        from temp2;


        update sige_asistencia_declarada A, temp2 B
        set estado_pago = 1
        where   A.estado_pago = 2 and
                A.ano_escolar = B.ano_escolar and
                A.mes_pago = B.mes_pago and
                A.mes_escolar = B.mes_escolar and
                A.rbd = B.rbd and
                A.cod_ens = B.cod_ens and
                A.cod_gra = B.cod_gra and
                A.let_cur = B.let_cur;

    

end

go




/******************************************************************************************************************
/*      ASISTENCIA DECLARADA PIE 299
/******************************************************************************************************************


drop procedure sp_carga_asistencia_declarada_pie_299
go

CREATE PROCEDURE sp_carga_asistencia_declarada_pie_299(in intanio int, in intmespago int,in intmesescolar int, in intrbd integer)
NOT DETERMINISTIC
CONTAINS SQL
begin

    declare done int default false;

    declare crs_intmespago 	smallint;
    declare crs_mes_escolar	smallint;
    declare crs_rbd	integer;
    declare crs_cod_ens	smallint;
    declare crs_cod_gra	smallint;
    declare crs_let_cur	varchar(2);
    declare crs_ano_escolar	integer;
    declare crs_sal_run	varchar(20);
    declare crs_dia1	smallint;
    declare crs_dia2	smallint;
    declare crs_dia3	smallint;
    declare crs_dia4	smallint;
    declare crs_dia5	smallint;
    declare crs_dia6	smallint;
    declare crs_dia7	smallint;
    declare crs_dia8	smallint;
    declare crs_dia9	smallint;
    declare crs_dia10	smallint;
    declare crs_dia11	smallint;
    declare crs_dia12	smallint;
    declare crs_dia13	smallint;
    declare crs_dia14	smallint;
    declare crs_dia15	smallint;
    declare crs_dia16	smallint;
    declare crs_dia17	smallint;
    declare crs_dia18	smallint;
    declare crs_dia19	smallint;
    declare crs_dia20	smallint;
    declare crs_dia21	smallint;
    declare crs_dia22	smallint;
    declare crs_dia23	smallint;
    declare crs_dia24	smallint;
    declare crs_dia25	smallint;
    declare crs_dia26	smallint;
    declare crs_dia27	smallint;
    declare crs_dia28	smallint;
    declare crs_dia29 	smallint;
    declare crs_dia30	smallint;
    declare crs_dia31	smallint;
    declare crs_dias_trabajados	smallint;
    declare crs_asis_promedio	decimal(10,4);
    declare crs_estado_declaracion	smallint;
    declare crs_dias_asistidos	smallint;
    declare crs_fecha_incorporacion	date;
    declare crs_estado_colision	smallint;
    declare crs_estado_pago	smallint;
    declare crs_contador	integer default 0;
    declare crs_regimen_sep integer;
    declare crs_tipo_alumno integer;
    declare crs_orden_matricula integer;
    declare crs_curso_actual	varchar(30) default '';
    declare crs_curso_aux		varchar(30) default '';
    declare crs_exe smallint;
    declare crs_tipo_aula smallint;
    declare vintalumno_retirado smallint;
    declare vintasistencia_duplicada smallint;
    declare vdiastrabajados_duplicado varchar(250) default '';
    declare crs_aplica_jecd smallint default 0;
    declare crs_cod_ens_subv smallint default 0;
    declare crs_cod_gra_subv smallint default 0;
    declare count_cursor integer default 0 ;
    declare ptotal_asis integer default 0 ;
    declare vfacuse decimal(7,5) default 0 ;
    declare vvaloruse decimal(10,4) default 0 ;
    declare vdiastrabajados_duplicado_palabra varchar(4000);
    declare vmaxcurso integer default 0;
    declare estado_pago integer default 0;
    declare crs_monto_subv_normal integer default 0;


    declare cursor_asistencia cursor for
                  select sa.mes_escolar,sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur , sa.ano_escolar, sa.sal_run , sa.dia1, sa.dia2 ,  sa.dia3, sa.dia4,sa.dia5 , sa.dia6 , sa.dia7 ,sa.dia8 ,  sa.dia9 , sa.dia10, sa.dia11 , sa.dia12, sa.dia13 , sa.dia14 ,sa.dia15,sa.dia16 ,  sa.dia17 ,  sa.dia18 ,  sa.dia19, sa.dia20 ,  sa.dia21,  sa.dia22 ,  sa.dia23, sa.dia24 ,  sa.dia25 , sa.dia26 ,  sa.dia27  , sa.dia28 , sa.dia29  ,  sa.dia30 , sa.dia31 ,  sa.dias_trabajados , sa.asis_promedio ,  sa.estado_declaracion  ,  sa.dias_asistidos, sa.fecha_matricula, sa.regimen_sep,sa.tipo_alumno,sa.orden_matricula,sa.tipo_aula,sa.jecd,sa.cod_ens_subv,sa.cod_gra_subv,sa.monto_subv_normal,sa.estado_colision,sa.estado_pago, sa.asis_promedio
                        from  sige_asistencia_declarada sa, sige_pie_alumnos_uns sp
                        where   sa.rbd = sp.rbd 
                                and sa.sal_run = sp.sal_run
                                and sp.ano_escolar  = intanio
                                and sp.mes_pago     = intmespago
                                and sp.estado       = 1
                                and sp.convenio     = 1

                                and sa.ano_escolar  = intanio
                                and sa.estado_pago  = 1
                                and sa.mes_pago     = intmespago
                                and sa.cod_ens      = 299
                                and sa.mes_escolar  = 3
                                and sa.habilitado_subv = 1
                                and sa.estado_declaracion in (2,3)
                        order by sa.rbd, sa.cod_ens,sa.cod_gra, sa.let_cur,sa.orden_matricula ;

    declare continue handler for not found set done = true; 

    OPEN cursor_asistencia;
        read_loop_1:LOOP

             FETCH cursor_asistencia INTO crs_mes_escolar,crs_rbd, crs_cod_ens,crs_cod_gra, crs_let_cur , crs_ano_escolar, crs_sal_run , crs_dia1, crs_dia2 ,  crs_dia3, crs_dia4,crs_dia5 , crs_dia6 , crs_dia7 ,crs_dia8 ,  crs_dia9 , crs_dia10, crs_dia11 , crs_dia12, crs_dia13 , crs_dia14 ,crs_dia15,crs_dia16 ,  crs_dia17 ,  crs_dia18 ,  crs_dia19, crs_dia20 ,  crs_dia21,  crs_dia22 ,  crs_dia23, crs_dia24 ,  crs_dia25 , crs_dia26 ,  crs_dia27  , crs_dia28 , crs_dia29  ,  crs_dia30 , crs_dia31 ,  crs_dias_trabajados , crs_asis_promedio ,  crs_estado_declaracion  ,  crs_dias_asistidos,crs_fecha_incorporacion, crs_regimen_sep,crs_tipo_alumno,crs_orden_matricula,crs_tipo_aula,crs_aplica_jecd,crs_cod_ens_subv,crs_cod_gra_subv,crs_monto_subv_normal,vintasistencia_duplicada,crs_estado_pago,crs_asis_promedio; 

             IF done THEN
                    leave read_loop_1;
             END IF;
   
             SET crs_curso_actual = concat(cast(crs_rbd as char),cast(crs_cod_ens as char),cast(crs_cod_gra as char),cast(crs_let_cur as char));
			
           SET vintalumno_retirado = if(crs_dia1=1,1,0)+ if(crs_dia2=1,1,0)+ if(crs_dia3=1,1,0)+ if(crs_dia4=1,1,0)+ if(crs_dia5=1,1,0)+ if(crs_dia6=1,1,0)+ if(crs_dia7=1,1,0)+ if(crs_dia8=1,1,0)+ if(crs_dia9=1,1,0)+ if(crs_dia10=1,1,0)+ if(crs_dia11=1,1,0)+ if(crs_dia12=1,1,0)+ if(crs_dia13=1,1,0)+ if(crs_dia14=1,1,0)+ if(crs_dia15=1,1,0)+ if(crs_dia16=1,1,0)+ if(crs_dia17=1,1,0)+ if(crs_dia18=1,1,0)+ if(crs_dia19=1,1,0)+ if(crs_dia20=1,1,0)+ if(crs_dia21=1,1,0)+ if(crs_dia22=1,1,0)+ if(crs_dia23=1,1,0)+ if(crs_dia24=1,1,0)+ if(crs_dia25=1,1,0)+ if(crs_dia26=1,1,0)+ if(crs_dia27=1,1,0)+ if(crs_dia28=1,1,0)+ if(crs_dia29=1,1,0)+ if(crs_dia30=1,1,0)+ if(crs_dia31=1,1,0); 

           IF (vintalumno_retirado > 0)THEN
                    IF(crs_cod_ens = 299)THEN
                        SET vmaxcurso = 15;
                    ELSE
                        SET vmaxcurso = 45;
                    END IF;

                    IF(crs_exe <= vmaxcurso )THEN
					insert into sige_asistencia_declarada_pie(mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur, ano_escolar, sal_run, dia1, dia2, dia3, dia4, dia5, dia6, dia7, dia8, dia9, dia10, dia11, dia12, dia13, dia14, dia15, dia16, dia17, dia18, dia19, dia20, dia21, dia22, dia23, dia24, dia25, dia26, dia27, dia28, dia29, dia30, dia31, dias_trabajados, asis_promedio, estado_declaracion, dias_asistidos, estado_pago, fecha_matricula, estado_colision,regimen_sep,tipo_alumno,orden_matricula,tipo_aula,jecd,cod_ens_subv,cod_gra_subv,monto_subv_normal)
					values (intmespago,crs_mes_escolar,crs_rbd, crs_cod_ens,crs_cod_gra, crs_let_cur , crs_ano_escolar, crs_sal_run , crs_dia1, crs_dia2 ,  crs_dia3, crs_dia4,crs_dia5 , crs_dia6 , crs_dia7 ,crs_dia8 ,  crs_dia9 , crs_dia10, crs_dia11 , crs_dia12, crs_dia13 , crs_dia14 ,crs_dia15,crs_dia16 ,  crs_dia17 ,  crs_dia18 ,  crs_dia19, crs_dia20 ,  crs_dia21,  crs_dia22 ,  crs_dia23, crs_dia24 ,  crs_dia25 , crs_dia26 ,  crs_dia27  , crs_dia28 , crs_dia29  ,  crs_dia30 , crs_dia31 ,  crs_dias_trabajados , crs_asis_promedio ,  crs_estado_declaracion  ,  crs_dias_asistidos,1, crs_fecha_incorporacion, vintasistencia_duplicada,crs_regimen_sep,crs_tipo_alumno,crs_orden_matricula,crs_tipo_aula,crs_aplica_jecd,crs_cod_ens_subv,crs_cod_gra_subv,crs_monto_subv_normal);			
                    ELSE
					insert into sige_asistencia_declarada_pie(mes_pago, mes_escolar, rbd, cod_ens, cod_gra, let_cur, ano_escolar, sal_run, dia1, dia2, dia3, dia4, dia5, dia6, dia7, dia8, dia9, dia10, dia11, dia12, dia13, dia14, dia15, dia16, dia17, dia18, dia19, dia20, dia21, dia22, dia23, dia24, dia25, dia26, dia27, dia28, dia29, dia30, dia31, dias_trabajados, asis_promedio, estado_declaracion, dias_asistidos, estado_pago, fecha_matricula, estado_colision,regimen_sep,tipo_alumno,orden_matricula,tipo_aula,jecd,cod_ens_subv,cod_gra_subv,monto_subv_normal)
					values (intmespago,crs_mes_escolar,crs_rbd, crs_cod_ens,crs_cod_gra, crs_let_cur , crs_ano_escolar, crs_sal_run , crs_dia1, crs_dia2 ,  crs_dia3, crs_dia4,crs_dia5 , crs_dia6 , crs_dia7 ,crs_dia8 ,  crs_dia9 , crs_dia10, crs_dia11 , crs_dia12, crs_dia13 , crs_dia14 ,crs_dia15,crs_dia16 ,  crs_dia17 ,  crs_dia18 ,  crs_dia19, crs_dia20 ,  crs_dia21,  crs_dia22 ,  crs_dia23, crs_dia24 ,  crs_dia25 , crs_dia26 ,  crs_dia27  , crs_dia28 , crs_dia29  ,  crs_dia30 , crs_dia31 ,  crs_dias_trabajados , crs_asis_promedio ,  crs_estado_declaracion  ,  crs_dias_asistidos,2 , crs_fecha_incorporacion, vintasistencia_duplicada,crs_regimen_sep,crs_tipo_alumno,crs_orden_matricula,crs_tipo_aula,crs_aplica_jecd,crs_cod_ens_subv,crs_cod_gra_subv,crs_monto_subv_normal);						
                    END IF;

           END IF;
			
           SET crs_curso_aux 	= concat(cast(crs_rbd as char),cast(crs_cod_ens as char),cast(crs_cod_gra as char),cast(crs_let_cur as char));
		   SET crs_exe          = crs_exe + 1;
		   SET crs_contador     = crs_contador +1;


        END LOOP;
    CLOSE cursor_asistencia;

end




/******************************************************************************************************************
/*      MARCA TIPO AULA = 2
/******************************************************************************************************************

call sp_extraccion_tipo_aula(2014,8,3)

drop procedure sp_extraccion_tipo_aula
go



CREATE PROCEDURE sp_extraccion_tipo_aula(in pano_escolar int, in pmes_pago int,in pmes_actual int)
NOT DETERMINISTIC
CONTAINS SQL
begin

	drop table if exists temp1;
        create temporary table temp1 engine=memory as(
            SELECT SEC.ano_escolar, pmes_pago mes_pago, pmes_actual MES_ESCOLAR,SEC.RBD,SEC.COD_ENS,SEC.COD_GRA,SEC.LET_CUR,SEC.TIPO_AULA
            FROM SIGE_ESTRUCTURA_CURSO  SEC
            WHERE ANO_ESCOLAR = pano_escolar
                and TIPO_AULA = 2
                AND SEC.RBD < 60000
        );

    create index  idx_tmp on temp1(ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur);


       
       UPDATE  sige_asistencia_declarada A,temp1 B
       SET A.TIPO_AULA = 2
       where A.ANO_ESCOLAR = B.ANO_ESCOLAR AND
            A.MES_PAGO = B.MES_PAGO AND
            A.RBD = B.RBD AND
            A.COD_ENS = B.COD_ENS AND
            A.COD_GRA = B.COD_GRA AND
            A.LET_CUR = B.LET_CUR and
            A.ANO_ESCOLAR = pano_escolar and
            A.MES_PAGO = pmes_pago and
            A.MES_ESCOLAR = pmes_actual
;

    SELECT COUNT(*)
    FROM SIGE_ASISTENCIA_DECLARADA
    WHERE ANO_ESCOLAR   = pano_escolar AND
          MES_PAGO      = pmes_pago AND
          MES_ESCOLAR   = pmes_actual AND
          TIPO_AULA = 2;
    

end


/******************************************************************************************************************
/*      HABILITADO SUBVENCIONES
/******************************************************************************************************************


--drop procedure sp_extraccion_habilitado_subv
go

--call sp_extraccion_habilitado_subv(2015,4,3); 
go

CREATE PROCEDURE sp_extraccion_habilitado_subv(in pano_escolar int, in pmes_pago int,in pmes_actual int)
NOT DETERMINISTIC
CONTAINS SQL
begin

	drop table if exists temp1;
        create temporary table temp1 engine=memory as(
            SELECT distinct SAD.ano_escolar, SAD.mes_pago, SAD.MES_ESCOLAR, sad.rbd,sad.COD_ENS,sad.COD_GRA,sad.LET_CUR,SEC.HABILITADO_SUBV
            FROM SIGE_ASISTENCIA_DECLARADA sad inner JOIN SIGE_ESTRUCTURA_CURSO sec
                                                        on sad.ANO_ESCOLAR = sec.ANO_ESCOLAR
                                                        and sad.RBD = sec.RBD
                                                        and sad.COD_ENS = sec.COD_ENS
                                                        and sad.COD_GRA = sec.COD_GRA
                                                         and trim(sad.LET_CUR) = trim(sec.LET_CUR)
                                                        and (sec.ESTADO_HABILITACION = 99 or (sec.ESTADO_HABILITACION IN (0,1) and SEC.HABILITADO_SUBV = 0))
            WHERE sad.ANO_ESCOLAR = pano_escolar
            and sad.MES_PAGO 	  = pmes_pago
            and sad.MES_ESCOLAR   = pmes_actual 
        );

        create index  idx_tmp on temp1(ano_escolar,mes_pago,mes_escolar,rbd,cod_ens,cod_gra,let_cur);


       
       UPDATE  sige_asistencia_declarada A,temp1 B
       SET A.HABILITADO_SUBV = B.HABILITADO_SUBV
       where A.ANO_ESCOLAR = B.ANO_ESCOLAR AND
            A.MES_PAGO = B.MES_PAGO AND
            A.RBD = B.RBD AND
            A.COD_ENS = B.COD_ENS AND
            A.COD_GRA = B.COD_GRA AND
            A.LET_CUR = B.LET_CUR and
            A.ANO_ESCOLAR = pano_escolar and
            A.MES_PAGO = pmes_pago and
            A.MES_ESCOLAR = pmes_actual
;

   
    

end


