/*conteo de 1° super job*/
SELECT REGIMEN_SEP,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 4
and MES_ESCOLAR =3
group by REGIMEN_SEP
go
SELECT ESTADO_COLISION,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =3
group by ESTADO_COLISION
go
go
SELECT TIPO_ALUMNO,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 4
and MES_ESCOLAR =3
group by TIPO_ALUMNO

go
SELECT ORDEN_MATRICULA,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =4
group by ORDEN_MATRICULA

go
SELECT JECD,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =4
group by JECD
with ur
go
SELECT TIPO_AULA,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =4
group by TIPO_AULA
with ur
go
SELECT COD_ENS_SUBV,COD_GRA_SUBV,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 4
and MES_ESCOLAR =3
group by COD_ENS_SUBV,COD_GRA_SUBV
with ur
go
SELECT HABILITADO_SUBV,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =4
group by HABILITADO_SUBV
with ur
go
SELECT ESTADO_PAGO,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =4
group by ESTADO_PAGO
with ur
go
SELECT TIPO_ALUMNO,count(*) 
FROM SIGE_ASISTENCIA_DECLARADA
where ANO_ESCOLAR = 2014
and MES_PAGO = 5
and MES_ESCOLAR =3
group by TIPO_ALUMNO
with ur
go
SELECT count(*) FROM SIGE_ASISTENCIA_DECLARADA_MULTIDEFICIT 
WHERE ANO_ESCOLAR = 2014
and MES_PAGO = 4
go



SELECT MES_ASIST,count(*)
FROM SIGE_ASISTENCIA_DECLARADA_NORMAL_SIN_PIE_POSEIDON
WHERE ANIO_ASIST = 2014
and MES_PAGO = 5
group by MES_ASIST 
with ur
go

SELECT MES_ASIST,count(*)
FROM SIGE_ASISTENCIA_DECLARADA_SEP_POSEIDON
WHERE ANIO_ASIST = 2014
and MES_PAGO = 5
group by MES_ASIST 
with ur